// Code generated by ent, DO NOT EDIT.

package paymentproviderinstance

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the paymentproviderinstance type in the database.
	Label = "payment_provider_instance"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProviderKey holds the string denoting the provider_key field in the database.
	FieldProviderKey = "provider_key"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldConfigEncrypted holds the string denoting the config_encrypted field in the database.
	FieldConfigEncrypted = "config_encrypted"
	// FieldSupportedTypes holds the string denoting the supported_types field in the database.
	FieldSupportedTypes = "supported_types"
	// FieldBalanceCreditRate holds the string denoting the balance_credit_rate field in the database.
	FieldBalanceCreditRate = "balance_credit_rate"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldSortOrder holds the string denoting the sort_order field in the database.
	FieldSortOrder = "sort_order"
	// FieldLimits holds the string denoting the limits field in the database.
	FieldLimits = "limits"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the paymentproviderinstance in the database.
	Table = "payment_provider_instances"
)

// Columns holds all SQL columns for paymentproviderinstance fields.
var Columns = []string{
	FieldID,
	FieldProviderKey,
	FieldName,
	FieldConfigEncrypted,
	FieldSupportedTypes,
	FieldBalanceCreditRate,
	FieldEnabled,
	FieldSortOrder,
	FieldLimits,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ProviderKeyValidator is a validator for the "provider_key" field. It is called by the builders before save.
	ProviderKeyValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultSupportedTypes holds the default value on creation for the "supported_types" field.
	DefaultSupportedTypes string
	// SupportedTypesValidator is a validator for the "supported_types" field. It is called by the builders before save.
	SupportedTypesValidator func(string) error
	// DefaultBalanceCreditRate holds the default value on creation for the "balance_credit_rate" field.
	DefaultBalanceCreditRate float64
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultSortOrder holds the default value on creation for the "sort_order" field.
	DefaultSortOrder int
	// DefaultLimits holds the default value on creation for the "limits" field.
	DefaultLimits string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the PaymentProviderInstance queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProviderKey orders the results by the provider_key field.
func ByProviderKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderKey, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByConfigEncrypted orders the results by the config_encrypted field.
func ByConfigEncrypted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfigEncrypted, opts...).ToFunc()
}

// BySupportedTypes orders the results by the supported_types field.
func BySupportedTypes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSupportedTypes, opts...).ToFunc()
}

// ByBalanceCreditRate orders the results by the balance_credit_rate field.
func ByBalanceCreditRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceCreditRate, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// BySortOrder orders the results by the sort_order field.
func BySortOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortOrder, opts...).ToFunc()
}

// ByLimits orders the results by the limits field.
func ByLimits(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLimits, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
