// Code generated by ent, DO NOT EDIT.

package paymentorder

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the paymentorder type in the database.
	Label = "payment_order"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldUserEmail holds the string denoting the user_email field in the database.
	FieldUserEmail = "user_email"
	// FieldUserName holds the string denoting the user_name field in the database.
	FieldUserName = "user_name"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldPayAmount holds the string denoting the pay_amount field in the database.
	FieldPayAmount = "pay_amount"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldBalanceCreditRate holds the string denoting the balance_credit_rate field in the database.
	FieldBalanceCreditRate = "balance_credit_rate"
	// FieldFeeRate holds the string denoting the fee_rate field in the database.
	FieldFeeRate = "fee_rate"
	// FieldRechargeCode holds the string denoting the recharge_code field in the database.
	FieldRechargeCode = "recharge_code"
	// FieldOrderType holds the string denoting the order_type field in the database.
	FieldOrderType = "order_type"
	// FieldPlanID holds the string denoting the plan_id field in the database.
	FieldPlanID = "plan_id"
	// FieldSubscriptionGroupID holds the string denoting the subscription_group_id field in the database.
	FieldSubscriptionGroupID = "subscription_group_id"
	// FieldSubscriptionDays holds the string denoting the subscription_days field in the database.
	FieldSubscriptionDays = "subscription_days"
	// FieldOutTradeNo holds the string denoting the out_trade_no field in the database.
	FieldOutTradeNo = "out_trade_no"
	// FieldPaymentType holds the string denoting the payment_type field in the database.
	FieldPaymentType = "payment_type"
	// FieldProviderKey holds the string denoting the provider_key field in the database.
	FieldProviderKey = "provider_key"
	// FieldProviderInstanceID holds the string denoting the provider_instance_id field in the database.
	FieldProviderInstanceID = "provider_instance_id"
	// FieldProviderSnapshotEncrypted holds the string denoting the provider_snapshot_encrypted field in the database.
	FieldProviderSnapshotEncrypted = "provider_snapshot_encrypted"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldPaymentTradeNo holds the string denoting the payment_trade_no field in the database.
	FieldPaymentTradeNo = "payment_trade_no"
	// FieldPayURL holds the string denoting the pay_url field in the database.
	FieldPayURL = "pay_url"
	// FieldQrCode holds the string denoting the qr_code field in the database.
	FieldQrCode = "qr_code"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldPaidAt holds the string denoting the paid_at field in the database.
	FieldPaidAt = "paid_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldFailedAt holds the string denoting the failed_at field in the database.
	FieldFailedAt = "failed_at"
	// FieldFailedReason holds the string denoting the failed_reason field in the database.
	FieldFailedReason = "failed_reason"
	// FieldRefundMode holds the string denoting the refund_mode field in the database.
	FieldRefundMode = "refund_mode"
	// FieldRefundAmount holds the string denoting the refund_amount field in the database.
	FieldRefundAmount = "refund_amount"
	// FieldRefundReason holds the string denoting the refund_reason field in the database.
	FieldRefundReason = "refund_reason"
	// FieldRefundExternalReference holds the string denoting the refund_external_reference field in the database.
	FieldRefundExternalReference = "refund_external_reference"
	// FieldRefundRequestedBy holds the string denoting the refund_requested_by field in the database.
	FieldRefundRequestedBy = "refund_requested_by"
	// FieldRefundRequestedAt holds the string denoting the refund_requested_at field in the database.
	FieldRefundRequestedAt = "refund_requested_at"
	// FieldRefundProviderCallStartedAt holds the string denoting the refund_provider_call_started_at field in the database.
	FieldRefundProviderCallStartedAt = "refund_provider_call_started_at"
	// FieldRefundedAt holds the string denoting the refunded_at field in the database.
	FieldRefundedAt = "refunded_at"
	// FieldRefundID holds the string denoting the refund_id field in the database.
	FieldRefundID = "refund_id"
	// FieldRefundEntitlementReversed holds the string denoting the refund_entitlement_reversed field in the database.
	FieldRefundEntitlementReversed = "refund_entitlement_reversed"
	// FieldRefundEntitlementSnapshot holds the string denoting the refund_entitlement_snapshot field in the database.
	FieldRefundEntitlementSnapshot = "refund_entitlement_snapshot"
	// FieldRefundForce holds the string denoting the refund_force field in the database.
	FieldRefundForce = "refund_force"
	// FieldRefundError holds the string denoting the refund_error field in the database.
	FieldRefundError = "refund_error"
	// FieldClientIP holds the string denoting the client_ip field in the database.
	FieldClientIP = "client_ip"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the paymentorder in the database.
	Table = "payment_orders"
)

// Columns holds all SQL columns for paymentorder fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldUserEmail,
	FieldUserName,
	FieldAmount,
	FieldPayAmount,
	FieldCurrency,
	FieldBalanceCreditRate,
	FieldFeeRate,
	FieldRechargeCode,
	FieldOrderType,
	FieldPlanID,
	FieldSubscriptionGroupID,
	FieldSubscriptionDays,
	FieldOutTradeNo,
	FieldPaymentType,
	FieldProviderKey,
	FieldProviderInstanceID,
	FieldProviderSnapshotEncrypted,
	FieldStatus,
	FieldPaymentTradeNo,
	FieldPayURL,
	FieldQrCode,
	FieldExpiresAt,
	FieldPaidAt,
	FieldCompletedAt,
	FieldFailedAt,
	FieldFailedReason,
	FieldRefundMode,
	FieldRefundAmount,
	FieldRefundReason,
	FieldRefundExternalReference,
	FieldRefundRequestedBy,
	FieldRefundRequestedAt,
	FieldRefundProviderCallStartedAt,
	FieldRefundedAt,
	FieldRefundID,
	FieldRefundEntitlementReversed,
	FieldRefundEntitlementSnapshot,
	FieldRefundForce,
	FieldRefundError,
	FieldClientIP,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UserEmailValidator is a validator for the "user_email" field. It is called by the builders before save.
	UserEmailValidator func(string) error
	// DefaultUserName holds the default value on creation for the "user_name" field.
	DefaultUserName string
	// UserNameValidator is a validator for the "user_name" field. It is called by the builders before save.
	UserNameValidator func(string) error
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	CurrencyValidator func(string) error
	// DefaultBalanceCreditRate holds the default value on creation for the "balance_credit_rate" field.
	DefaultBalanceCreditRate float64
	// DefaultFeeRate holds the default value on creation for the "fee_rate" field.
	DefaultFeeRate float64
	// RechargeCodeValidator is a validator for the "recharge_code" field. It is called by the builders before save.
	RechargeCodeValidator func(string) error
	// DefaultOrderType holds the default value on creation for the "order_type" field.
	DefaultOrderType string
	// OrderTypeValidator is a validator for the "order_type" field. It is called by the builders before save.
	OrderTypeValidator func(string) error
	// OutTradeNoValidator is a validator for the "out_trade_no" field. It is called by the builders before save.
	OutTradeNoValidator func(string) error
	// PaymentTypeValidator is a validator for the "payment_type" field. It is called by the builders before save.
	PaymentTypeValidator func(string) error
	// ProviderKeyValidator is a validator for the "provider_key" field. It is called by the builders before save.
	ProviderKeyValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultPaymentTradeNo holds the default value on creation for the "payment_trade_no" field.
	DefaultPaymentTradeNo string
	// PaymentTradeNoValidator is a validator for the "payment_trade_no" field. It is called by the builders before save.
	PaymentTradeNoValidator func(string) error
	// DefaultRefundMode holds the default value on creation for the "refund_mode" field.
	DefaultRefundMode string
	// RefundModeValidator is a validator for the "refund_mode" field. It is called by the builders before save.
	RefundModeValidator func(string) error
	// DefaultRefundAmount holds the default value on creation for the "refund_amount" field.
	DefaultRefundAmount float64
	// RefundExternalReferenceValidator is a validator for the "refund_external_reference" field. It is called by the builders before save.
	RefundExternalReferenceValidator func(string) error
	// DefaultRefundRequestedBy holds the default value on creation for the "refund_requested_by" field.
	DefaultRefundRequestedBy string
	// RefundRequestedByValidator is a validator for the "refund_requested_by" field. It is called by the builders before save.
	RefundRequestedByValidator func(string) error
	// DefaultRefundID holds the default value on creation for the "refund_id" field.
	DefaultRefundID string
	// RefundIDValidator is a validator for the "refund_id" field. It is called by the builders before save.
	RefundIDValidator func(string) error
	// DefaultRefundEntitlementReversed holds the default value on creation for the "refund_entitlement_reversed" field.
	DefaultRefundEntitlementReversed bool
	// DefaultRefundEntitlementSnapshot holds the default value on creation for the "refund_entitlement_snapshot" field.
	DefaultRefundEntitlementSnapshot string
	// DefaultRefundForce holds the default value on creation for the "refund_force" field.
	DefaultRefundForce bool
	// DefaultClientIP holds the default value on creation for the "client_ip" field.
	DefaultClientIP string
	// ClientIPValidator is a validator for the "client_ip" field. It is called by the builders before save.
	ClientIPValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the PaymentOrder queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByUserEmail orders the results by the user_email field.
func ByUserEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserEmail, opts...).ToFunc()
}

// ByUserName orders the results by the user_name field.
func ByUserName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserName, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByPayAmount orders the results by the pay_amount field.
func ByPayAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayAmount, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByBalanceCreditRate orders the results by the balance_credit_rate field.
func ByBalanceCreditRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceCreditRate, opts...).ToFunc()
}

// ByFeeRate orders the results by the fee_rate field.
func ByFeeRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeeRate, opts...).ToFunc()
}

// ByRechargeCode orders the results by the recharge_code field.
func ByRechargeCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRechargeCode, opts...).ToFunc()
}

// ByOrderType orders the results by the order_type field.
func ByOrderType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderType, opts...).ToFunc()
}

// ByPlanID orders the results by the plan_id field.
func ByPlanID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlanID, opts...).ToFunc()
}

// BySubscriptionGroupID orders the results by the subscription_group_id field.
func BySubscriptionGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubscriptionGroupID, opts...).ToFunc()
}

// BySubscriptionDays orders the results by the subscription_days field.
func BySubscriptionDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubscriptionDays, opts...).ToFunc()
}

// ByOutTradeNo orders the results by the out_trade_no field.
func ByOutTradeNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutTradeNo, opts...).ToFunc()
}

// ByPaymentType orders the results by the payment_type field.
func ByPaymentType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaymentType, opts...).ToFunc()
}

// ByProviderKey orders the results by the provider_key field.
func ByProviderKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderKey, opts...).ToFunc()
}

// ByProviderInstanceID orders the results by the provider_instance_id field.
func ByProviderInstanceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderInstanceID, opts...).ToFunc()
}

// ByProviderSnapshotEncrypted orders the results by the provider_snapshot_encrypted field.
func ByProviderSnapshotEncrypted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderSnapshotEncrypted, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByPaymentTradeNo orders the results by the payment_trade_no field.
func ByPaymentTradeNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaymentTradeNo, opts...).ToFunc()
}

// ByPayURL orders the results by the pay_url field.
func ByPayURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayURL, opts...).ToFunc()
}

// ByQrCode orders the results by the qr_code field.
func ByQrCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQrCode, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByPaidAt orders the results by the paid_at field.
func ByPaidAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaidAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByFailedAt orders the results by the failed_at field.
func ByFailedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailedAt, opts...).ToFunc()
}

// ByFailedReason orders the results by the failed_reason field.
func ByFailedReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailedReason, opts...).ToFunc()
}

// ByRefundMode orders the results by the refund_mode field.
func ByRefundMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefundMode, opts...).ToFunc()
}

// ByRefundAmount orders the results by the refund_amount field.
func ByRefundAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefundAmount, opts...).ToFunc()
}

// ByRefundReason orders the results by the refund_reason field.
func ByRefundReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefundReason, opts...).ToFunc()
}

// ByRefundExternalReference orders the results by the refund_external_reference field.
func ByRefundExternalReference(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefundExternalReference, opts...).ToFunc()
}

// ByRefundRequestedBy orders the results by the refund_requested_by field.
func ByRefundRequestedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefundRequestedBy, opts...).ToFunc()
}

// ByRefundRequestedAt orders the results by the refund_requested_at field.
func ByRefundRequestedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefundRequestedAt, opts...).ToFunc()
}

// ByRefundProviderCallStartedAt orders the results by the refund_provider_call_started_at field.
func ByRefundProviderCallStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefundProviderCallStartedAt, opts...).ToFunc()
}

// ByRefundedAt orders the results by the refunded_at field.
func ByRefundedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefundedAt, opts...).ToFunc()
}

// ByRefundID orders the results by the refund_id field.
func ByRefundID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefundID, opts...).ToFunc()
}

// ByRefundEntitlementReversed orders the results by the refund_entitlement_reversed field.
func ByRefundEntitlementReversed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefundEntitlementReversed, opts...).ToFunc()
}

// ByRefundEntitlementSnapshot orders the results by the refund_entitlement_snapshot field.
func ByRefundEntitlementSnapshot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefundEntitlementSnapshot, opts...).ToFunc()
}

// ByRefundForce orders the results by the refund_force field.
func ByRefundForce(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefundForce, opts...).ToFunc()
}

// ByRefundError orders the results by the refund_error field.
func ByRefundError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefundError, opts...).ToFunc()
}

// ByClientIP orders the results by the client_ip field.
func ByClientIP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientIP, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
