version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '03:30'
      timezone: Etc/UTC
    groups:
      github-actions:
        patterns:
          - '*'
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore(actions)
