// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accesslevel"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// AccessLevelCreate is the builder for creating a AccessLevel entity.
type AccessLevelCreate struct {
	config
	mutation *AccessLevelMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *AccessLevelCreate) SetName(v string) *AccessLevelCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetRank sets the "rank" field.
func (_c *AccessLevelCreate) SetRank(v int) *AccessLevelCreate {
	_c.mutation.SetRank(v)
	return _c
}

// SetBalanceThreshold sets the "balance_threshold" field.
func (_c *AccessLevelCreate) SetBalanceThreshold(v float64) *AccessLevelCreate {
	_c.mutation.SetBalanceThreshold(v)
	return _c
}

// SetNillableBalanceThreshold sets the "balance_threshold" field if the given value is not nil.
func (_c *AccessLevelCreate) SetNillableBalanceThreshold(v *float64) *AccessLevelCreate {
	if v != nil {
		_c.SetBalanceThreshold(*v)
	}
	return _c
}

// SetPaygDiscountMultiplier sets the "payg_discount_multiplier" field.
func (_c *AccessLevelCreate) SetPaygDiscountMultiplier(v float64) *AccessLevelCreate {
	_c.mutation.SetPaygDiscountMultiplier(v)
	return _c
}

// SetNillablePaygDiscountMultiplier sets the "payg_discount_multiplier" field if the given value is not nil.
func (_c *AccessLevelCreate) SetNillablePaygDiscountMultiplier(v *float64) *AccessLevelCreate {
	if v != nil {
		_c.SetPaygDiscountMultiplier(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccessLevelCreate) SetCreatedAt(v time.Time) *AccessLevelCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccessLevelCreate) SetNillableCreatedAt(v *time.Time) *AccessLevelCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AccessLevelCreate) SetUpdatedAt(v time.Time) *AccessLevelCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AccessLevelCreate) SetNillableUpdatedAt(v *time.Time) *AccessLevelCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddAutoUserIDs adds the "auto_users" edge to the User entity by IDs.
func (_c *AccessLevelCreate) AddAutoUserIDs(ids ...int64) *AccessLevelCreate {
	_c.mutation.AddAutoUserIDs(ids...)
	return _c
}

// AddAutoUsers adds the "auto_users" edges to the User entity.
func (_c *AccessLevelCreate) AddAutoUsers(v ...*User) *AccessLevelCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAutoUserIDs(ids...)
}

// AddManualUserIDs adds the "manual_users" edge to the User entity by IDs.
func (_c *AccessLevelCreate) AddManualUserIDs(ids ...int64) *AccessLevelCreate {
	_c.mutation.AddManualUserIDs(ids...)
	return _c
}

// AddManualUsers adds the "manual_users" edges to the User entity.
func (_c *AccessLevelCreate) AddManualUsers(v ...*User) *AccessLevelCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddManualUserIDs(ids...)
}

// AddRequiredGroupIDs adds the "required_groups" edge to the Group entity by IDs.
func (_c *AccessLevelCreate) AddRequiredGroupIDs(ids ...int64) *AccessLevelCreate {
	_c.mutation.AddRequiredGroupIDs(ids...)
	return _c
}

// AddRequiredGroups adds the "required_groups" edges to the Group entity.
func (_c *AccessLevelCreate) AddRequiredGroups(v ...*Group) *AccessLevelCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRequiredGroupIDs(ids...)
}

// Mutation returns the AccessLevelMutation object of the builder.
func (_c *AccessLevelCreate) Mutation() *AccessLevelMutation {
	return _c.mutation
}

// Save creates the AccessLevel in the database.
func (_c *AccessLevelCreate) Save(ctx context.Context) (*AccessLevel, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccessLevelCreate) SaveX(ctx context.Context) *AccessLevel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccessLevelCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccessLevelCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccessLevelCreate) defaults() {
	if _, ok := _c.mutation.BalanceThreshold(); !ok {
		v := accesslevel.DefaultBalanceThreshold
		_c.mutation.SetBalanceThreshold(v)
	}
	if _, ok := _c.mutation.PaygDiscountMultiplier(); !ok {
		v := accesslevel.DefaultPaygDiscountMultiplier
		_c.mutation.SetPaygDiscountMultiplier(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := accesslevel.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := accesslevel.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccessLevelCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "AccessLevel.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := accesslevel.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AccessLevel.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Rank(); !ok {
		return &ValidationError{Name: "rank", err: errors.New(`ent: missing required field "AccessLevel.rank"`)}
	}
	if v, ok := _c.mutation.Rank(); ok {
		if err := accesslevel.RankValidator(v); err != nil {
			return &ValidationError{Name: "rank", err: fmt.Errorf(`ent: validator failed for field "AccessLevel.rank": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BalanceThreshold(); !ok {
		return &ValidationError{Name: "balance_threshold", err: errors.New(`ent: missing required field "AccessLevel.balance_threshold"`)}
	}
	if _, ok := _c.mutation.PaygDiscountMultiplier(); !ok {
		return &ValidationError{Name: "payg_discount_multiplier", err: errors.New(`ent: missing required field "AccessLevel.payg_discount_multiplier"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AccessLevel.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AccessLevel.updated_at"`)}
	}
	return nil
}

func (_c *AccessLevelCreate) sqlSave(ctx context.Context) (*AccessLevel, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccessLevelCreate) createSpec() (*AccessLevel, *sqlgraph.CreateSpec) {
	var (
		_node = &AccessLevel{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accesslevel.Table, sqlgraph.NewFieldSpec(accesslevel.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(accesslevel.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Rank(); ok {
		_spec.SetField(accesslevel.FieldRank, field.TypeInt, value)
		_node.Rank = value
	}
	if value, ok := _c.mutation.BalanceThreshold(); ok {
		_spec.SetField(accesslevel.FieldBalanceThreshold, field.TypeFloat64, value)
		_node.BalanceThreshold = value
	}
	if value, ok := _c.mutation.PaygDiscountMultiplier(); ok {
		_spec.SetField(accesslevel.FieldPaygDiscountMultiplier, field.TypeFloat64, value)
		_node.PaygDiscountMultiplier = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(accesslevel.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(accesslevel.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.AutoUsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accesslevel.AutoUsersTable,
			Columns: []string{accesslevel.AutoUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ManualUsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accesslevel.ManualUsersTable,
			Columns: []string{accesslevel.ManualUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RequiredGroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accesslevel.RequiredGroupsTable,
			Columns: []string{accesslevel.RequiredGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccessLevel.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccessLevelUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *AccessLevelCreate) OnConflict(opts ...sql.ConflictOption) *AccessLevelUpsertOne {
	_c.conflict = opts
	return &AccessLevelUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccessLevel.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccessLevelCreate) OnConflictColumns(columns ...string) *AccessLevelUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccessLevelUpsertOne{
		create: _c,
	}
}

type (
	// AccessLevelUpsertOne is the builder for "upsert"-ing
	//  one AccessLevel node.
	AccessLevelUpsertOne struct {
		create *AccessLevelCreate
	}

	// AccessLevelUpsert is the "OnConflict" setter.
	AccessLevelUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *AccessLevelUpsert) SetName(v string) *AccessLevelUpsert {
	u.Set(accesslevel.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AccessLevelUpsert) UpdateName() *AccessLevelUpsert {
	u.SetExcluded(accesslevel.FieldName)
	return u
}

// SetRank sets the "rank" field.
func (u *AccessLevelUpsert) SetRank(v int) *AccessLevelUpsert {
	u.Set(accesslevel.FieldRank, v)
	return u
}

// UpdateRank sets the "rank" field to the value that was provided on create.
func (u *AccessLevelUpsert) UpdateRank() *AccessLevelUpsert {
	u.SetExcluded(accesslevel.FieldRank)
	return u
}

// AddRank adds v to the "rank" field.
func (u *AccessLevelUpsert) AddRank(v int) *AccessLevelUpsert {
	u.Add(accesslevel.FieldRank, v)
	return u
}

// SetBalanceThreshold sets the "balance_threshold" field.
func (u *AccessLevelUpsert) SetBalanceThreshold(v float64) *AccessLevelUpsert {
	u.Set(accesslevel.FieldBalanceThreshold, v)
	return u
}

// UpdateBalanceThreshold sets the "balance_threshold" field to the value that was provided on create.
func (u *AccessLevelUpsert) UpdateBalanceThreshold() *AccessLevelUpsert {
	u.SetExcluded(accesslevel.FieldBalanceThreshold)
	return u
}

// AddBalanceThreshold adds v to the "balance_threshold" field.
func (u *AccessLevelUpsert) AddBalanceThreshold(v float64) *AccessLevelUpsert {
	u.Add(accesslevel.FieldBalanceThreshold, v)
	return u
}

// SetPaygDiscountMultiplier sets the "payg_discount_multiplier" field.
func (u *AccessLevelUpsert) SetPaygDiscountMultiplier(v float64) *AccessLevelUpsert {
	u.Set(accesslevel.FieldPaygDiscountMultiplier, v)
	return u
}

// UpdatePaygDiscountMultiplier sets the "payg_discount_multiplier" field to the value that was provided on create.
func (u *AccessLevelUpsert) UpdatePaygDiscountMultiplier() *AccessLevelUpsert {
	u.SetExcluded(accesslevel.FieldPaygDiscountMultiplier)
	return u
}

// AddPaygDiscountMultiplier adds v to the "payg_discount_multiplier" field.
func (u *AccessLevelUpsert) AddPaygDiscountMultiplier(v float64) *AccessLevelUpsert {
	u.Add(accesslevel.FieldPaygDiscountMultiplier, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccessLevelUpsert) SetUpdatedAt(v time.Time) *AccessLevelUpsert {
	u.Set(accesslevel.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccessLevelUpsert) UpdateUpdatedAt() *AccessLevelUpsert {
	u.SetExcluded(accesslevel.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AccessLevel.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccessLevelUpsertOne) UpdateNewValues() *AccessLevelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(accesslevel.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccessLevel.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccessLevelUpsertOne) Ignore() *AccessLevelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccessLevelUpsertOne) DoNothing() *AccessLevelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccessLevelCreate.OnConflict
// documentation for more info.
func (u *AccessLevelUpsertOne) Update(set func(*AccessLevelUpsert)) *AccessLevelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccessLevelUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *AccessLevelUpsertOne) SetName(v string) *AccessLevelUpsertOne {
	return u.Update(func(s *AccessLevelUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AccessLevelUpsertOne) UpdateName() *AccessLevelUpsertOne {
	return u.Update(func(s *AccessLevelUpsert) {
		s.UpdateName()
	})
}

// SetRank sets the "rank" field.
func (u *AccessLevelUpsertOne) SetRank(v int) *AccessLevelUpsertOne {
	return u.Update(func(s *AccessLevelUpsert) {
		s.SetRank(v)
	})
}

// AddRank adds v to the "rank" field.
func (u *AccessLevelUpsertOne) AddRank(v int) *AccessLevelUpsertOne {
	return u.Update(func(s *AccessLevelUpsert) {
		s.AddRank(v)
	})
}

// UpdateRank sets the "rank" field to the value that was provided on create.
func (u *AccessLevelUpsertOne) UpdateRank() *AccessLevelUpsertOne {
	return u.Update(func(s *AccessLevelUpsert) {
		s.UpdateRank()
	})
}

// SetBalanceThreshold sets the "balance_threshold" field.
func (u *AccessLevelUpsertOne) SetBalanceThreshold(v float64) *AccessLevelUpsertOne {
	return u.Update(func(s *AccessLevelUpsert) {
		s.SetBalanceThreshold(v)
	})
}

// AddBalanceThreshold adds v to the "balance_threshold" field.
func (u *AccessLevelUpsertOne) AddBalanceThreshold(v float64) *AccessLevelUpsertOne {
	return u.Update(func(s *AccessLevelUpsert) {
		s.AddBalanceThreshold(v)
	})
}

// UpdateBalanceThreshold sets the "balance_threshold" field to the value that was provided on create.
func (u *AccessLevelUpsertOne) UpdateBalanceThreshold() *AccessLevelUpsertOne {
	return u.Update(func(s *AccessLevelUpsert) {
		s.UpdateBalanceThreshold()
	})
}

// SetPaygDiscountMultiplier sets the "payg_discount_multiplier" field.
func (u *AccessLevelUpsertOne) SetPaygDiscountMultiplier(v float64) *AccessLevelUpsertOne {
	return u.Update(func(s *AccessLevelUpsert) {
		s.SetPaygDiscountMultiplier(v)
	})
}

// AddPaygDiscountMultiplier adds v to the "payg_discount_multiplier" field.
func (u *AccessLevelUpsertOne) AddPaygDiscountMultiplier(v float64) *AccessLevelUpsertOne {
	return u.Update(func(s *AccessLevelUpsert) {
		s.AddPaygDiscountMultiplier(v)
	})
}

// UpdatePaygDiscountMultiplier sets the "payg_discount_multiplier" field to the value that was provided on create.
func (u *AccessLevelUpsertOne) UpdatePaygDiscountMultiplier() *AccessLevelUpsertOne {
	return u.Update(func(s *AccessLevelUpsert) {
		s.UpdatePaygDiscountMultiplier()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccessLevelUpsertOne) SetUpdatedAt(v time.Time) *AccessLevelUpsertOne {
	return u.Update(func(s *AccessLevelUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccessLevelUpsertOne) UpdateUpdatedAt() *AccessLevelUpsertOne {
	return u.Update(func(s *AccessLevelUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *AccessLevelUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccessLevelCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccessLevelUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AccessLevelUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AccessLevelUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AccessLevelCreateBulk is the builder for creating many AccessLevel entities in bulk.
type AccessLevelCreateBulk struct {
	config
	err      error
	builders []*AccessLevelCreate
	conflict []sql.ConflictOption
}

// Save creates the AccessLevel entities in the database.
func (_c *AccessLevelCreateBulk) Save(ctx context.Context) ([]*AccessLevel, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccessLevel, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccessLevelMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccessLevelCreateBulk) SaveX(ctx context.Context) []*AccessLevel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccessLevelCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccessLevelCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccessLevel.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccessLevelUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *AccessLevelCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccessLevelUpsertBulk {
	_c.conflict = opts
	return &AccessLevelUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccessLevel.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccessLevelCreateBulk) OnConflictColumns(columns ...string) *AccessLevelUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccessLevelUpsertBulk{
		create: _c,
	}
}

// AccessLevelUpsertBulk is the builder for "upsert"-ing
// a bulk of AccessLevel nodes.
type AccessLevelUpsertBulk struct {
	create *AccessLevelCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AccessLevel.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccessLevelUpsertBulk) UpdateNewValues() *AccessLevelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(accesslevel.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccessLevel.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccessLevelUpsertBulk) Ignore() *AccessLevelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccessLevelUpsertBulk) DoNothing() *AccessLevelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccessLevelCreateBulk.OnConflict
// documentation for more info.
func (u *AccessLevelUpsertBulk) Update(set func(*AccessLevelUpsert)) *AccessLevelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccessLevelUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *AccessLevelUpsertBulk) SetName(v string) *AccessLevelUpsertBulk {
	return u.Update(func(s *AccessLevelUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AccessLevelUpsertBulk) UpdateName() *AccessLevelUpsertBulk {
	return u.Update(func(s *AccessLevelUpsert) {
		s.UpdateName()
	})
}

// SetRank sets the "rank" field.
func (u *AccessLevelUpsertBulk) SetRank(v int) *AccessLevelUpsertBulk {
	return u.Update(func(s *AccessLevelUpsert) {
		s.SetRank(v)
	})
}

// AddRank adds v to the "rank" field.
func (u *AccessLevelUpsertBulk) AddRank(v int) *AccessLevelUpsertBulk {
	return u.Update(func(s *AccessLevelUpsert) {
		s.AddRank(v)
	})
}

// UpdateRank sets the "rank" field to the value that was provided on create.
func (u *AccessLevelUpsertBulk) UpdateRank() *AccessLevelUpsertBulk {
	return u.Update(func(s *AccessLevelUpsert) {
		s.UpdateRank()
	})
}

// SetBalanceThreshold sets the "balance_threshold" field.
func (u *AccessLevelUpsertBulk) SetBalanceThreshold(v float64) *AccessLevelUpsertBulk {
	return u.Update(func(s *AccessLevelUpsert) {
		s.SetBalanceThreshold(v)
	})
}

// AddBalanceThreshold adds v to the "balance_threshold" field.
func (u *AccessLevelUpsertBulk) AddBalanceThreshold(v float64) *AccessLevelUpsertBulk {
	return u.Update(func(s *AccessLevelUpsert) {
		s.AddBalanceThreshold(v)
	})
}

// UpdateBalanceThreshold sets the "balance_threshold" field to the value that was provided on create.
func (u *AccessLevelUpsertBulk) UpdateBalanceThreshold() *AccessLevelUpsertBulk {
	return u.Update(func(s *AccessLevelUpsert) {
		s.UpdateBalanceThreshold()
	})
}

// SetPaygDiscountMultiplier sets the "payg_discount_multiplier" field.
func (u *AccessLevelUpsertBulk) SetPaygDiscountMultiplier(v float64) *AccessLevelUpsertBulk {
	return u.Update(func(s *AccessLevelUpsert) {
		s.SetPaygDiscountMultiplier(v)
	})
}

// AddPaygDiscountMultiplier adds v to the "payg_discount_multiplier" field.
func (u *AccessLevelUpsertBulk) AddPaygDiscountMultiplier(v float64) *AccessLevelUpsertBulk {
	return u.Update(func(s *AccessLevelUpsert) {
		s.AddPaygDiscountMultiplier(v)
	})
}

// UpdatePaygDiscountMultiplier sets the "payg_discount_multiplier" field to the value that was provided on create.
func (u *AccessLevelUpsertBulk) UpdatePaygDiscountMultiplier() *AccessLevelUpsertBulk {
	return u.Update(func(s *AccessLevelUpsert) {
		s.UpdatePaygDiscountMultiplier()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccessLevelUpsertBulk) SetUpdatedAt(v time.Time) *AccessLevelUpsertBulk {
	return u.Update(func(s *AccessLevelUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccessLevelUpsertBulk) UpdateUpdatedAt() *AccessLevelUpsertBulk {
	return u.Update(func(s *AccessLevelUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *AccessLevelUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccessLevelCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccessLevelCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccessLevelUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
