// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/accesslevel"
)

// AccessLevel is the model entity for the AccessLevel schema.
type AccessLevel struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Rank holds the value of the "rank" field.
	Rank int `json:"rank,omitempty"`
	// BalanceThreshold holds the value of the "balance_threshold" field.
	BalanceThreshold float64 `json:"balance_threshold,omitempty"`
	// PaygDiscountMultiplier holds the value of the "payg_discount_multiplier" field.
	PaygDiscountMultiplier float64 `json:"payg_discount_multiplier,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AccessLevelQuery when eager-loading is set.
	Edges        AccessLevelEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AccessLevelEdges holds the relations/edges for other nodes in the graph.
type AccessLevelEdges struct {
	// AutoUsers holds the value of the auto_users edge.
	AutoUsers []*User `json:"auto_users,omitempty"`
	// ManualUsers holds the value of the manual_users edge.
	ManualUsers []*User `json:"manual_users,omitempty"`
	// RequiredGroups holds the value of the required_groups edge.
	RequiredGroups []*Group `json:"required_groups,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// AutoUsersOrErr returns the AutoUsers value or an error if the edge
// was not loaded in eager-loading.
func (e AccessLevelEdges) AutoUsersOrErr() ([]*User, error) {
	if e.loadedTypes[0] {
		return e.AutoUsers, nil
	}
	return nil, &NotLoadedError{edge: "auto_users"}
}

// ManualUsersOrErr returns the ManualUsers value or an error if the edge
// was not loaded in eager-loading.
func (e AccessLevelEdges) ManualUsersOrErr() ([]*User, error) {
	if e.loadedTypes[1] {
		return e.ManualUsers, nil
	}
	return nil, &NotLoadedError{edge: "manual_users"}
}

// RequiredGroupsOrErr returns the RequiredGroups value or an error if the edge
// was not loaded in eager-loading.
func (e AccessLevelEdges) RequiredGroupsOrErr() ([]*Group, error) {
	if e.loadedTypes[2] {
		return e.RequiredGroups, nil
	}
	return nil, &NotLoadedError{edge: "required_groups"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccessLevel) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accesslevel.FieldBalanceThreshold, accesslevel.FieldPaygDiscountMultiplier:
			values[i] = new(sql.NullFloat64)
		case accesslevel.FieldID, accesslevel.FieldRank:
			values[i] = new(sql.NullInt64)
		case accesslevel.FieldName:
			values[i] = new(sql.NullString)
		case accesslevel.FieldCreatedAt, accesslevel.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccessLevel fields.
func (_m *AccessLevel) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accesslevel.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case accesslevel.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case accesslevel.FieldRank:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rank", values[i])
			} else if value.Valid {
				_m.Rank = int(value.Int64)
			}
		case accesslevel.FieldBalanceThreshold:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance_threshold", values[i])
			} else if value.Valid {
				_m.BalanceThreshold = value.Float64
			}
		case accesslevel.FieldPaygDiscountMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field payg_discount_multiplier", values[i])
			} else if value.Valid {
				_m.PaygDiscountMultiplier = value.Float64
			}
		case accesslevel.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case accesslevel.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccessLevel.
// This includes values selected through modifiers, order, etc.
func (_m *AccessLevel) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAutoUsers queries the "auto_users" edge of the AccessLevel entity.
func (_m *AccessLevel) QueryAutoUsers() *UserQuery {
	return NewAccessLevelClient(_m.config).QueryAutoUsers(_m)
}

// QueryManualUsers queries the "manual_users" edge of the AccessLevel entity.
func (_m *AccessLevel) QueryManualUsers() *UserQuery {
	return NewAccessLevelClient(_m.config).QueryManualUsers(_m)
}

// QueryRequiredGroups queries the "required_groups" edge of the AccessLevel entity.
func (_m *AccessLevel) QueryRequiredGroups() *GroupQuery {
	return NewAccessLevelClient(_m.config).QueryRequiredGroups(_m)
}

// Update returns a builder for updating this AccessLevel.
// Note that you need to call AccessLevel.Unwrap() before calling this method if this AccessLevel
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AccessLevel) Update() *AccessLevelUpdateOne {
	return NewAccessLevelClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AccessLevel entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AccessLevel) Unwrap() *AccessLevel {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccessLevel is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AccessLevel) String() string {
	var builder strings.Builder
	builder.WriteString("AccessLevel(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("rank=")
	builder.WriteString(fmt.Sprintf("%v", _m.Rank))
	builder.WriteString(", ")
	builder.WriteString("balance_threshold=")
	builder.WriteString(fmt.Sprintf("%v", _m.BalanceThreshold))
	builder.WriteString(", ")
	builder.WriteString("payg_discount_multiplier=")
	builder.WriteString(fmt.Sprintf("%v", _m.PaygDiscountMultiplier))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AccessLevels is a parsable slice of AccessLevel.
type AccessLevels []*AccessLevel
