// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accesslevel"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// AccessLevelUpdate is the builder for updating AccessLevel entities.
type AccessLevelUpdate struct {
	config
	hooks    []Hook
	mutation *AccessLevelMutation
}

// Where appends a list predicates to the AccessLevelUpdate builder.
func (_u *AccessLevelUpdate) Where(ps ...predicate.AccessLevel) *AccessLevelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *AccessLevelUpdate) SetName(v string) *AccessLevelUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AccessLevelUpdate) SetNillableName(v *string) *AccessLevelUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetRank sets the "rank" field.
func (_u *AccessLevelUpdate) SetRank(v int) *AccessLevelUpdate {
	_u.mutation.ResetRank()
	_u.mutation.SetRank(v)
	return _u
}

// SetNillableRank sets the "rank" field if the given value is not nil.
func (_u *AccessLevelUpdate) SetNillableRank(v *int) *AccessLevelUpdate {
	if v != nil {
		_u.SetRank(*v)
	}
	return _u
}

// AddRank adds value to the "rank" field.
func (_u *AccessLevelUpdate) AddRank(v int) *AccessLevelUpdate {
	_u.mutation.AddRank(v)
	return _u
}

// SetBalanceThreshold sets the "balance_threshold" field.
func (_u *AccessLevelUpdate) SetBalanceThreshold(v float64) *AccessLevelUpdate {
	_u.mutation.ResetBalanceThreshold()
	_u.mutation.SetBalanceThreshold(v)
	return _u
}

// SetNillableBalanceThreshold sets the "balance_threshold" field if the given value is not nil.
func (_u *AccessLevelUpdate) SetNillableBalanceThreshold(v *float64) *AccessLevelUpdate {
	if v != nil {
		_u.SetBalanceThreshold(*v)
	}
	return _u
}

// AddBalanceThreshold adds value to the "balance_threshold" field.
func (_u *AccessLevelUpdate) AddBalanceThreshold(v float64) *AccessLevelUpdate {
	_u.mutation.AddBalanceThreshold(v)
	return _u
}

// SetPaygDiscountMultiplier sets the "payg_discount_multiplier" field.
func (_u *AccessLevelUpdate) SetPaygDiscountMultiplier(v float64) *AccessLevelUpdate {
	_u.mutation.ResetPaygDiscountMultiplier()
	_u.mutation.SetPaygDiscountMultiplier(v)
	return _u
}

// SetNillablePaygDiscountMultiplier sets the "payg_discount_multiplier" field if the given value is not nil.
func (_u *AccessLevelUpdate) SetNillablePaygDiscountMultiplier(v *float64) *AccessLevelUpdate {
	if v != nil {
		_u.SetPaygDiscountMultiplier(*v)
	}
	return _u
}

// AddPaygDiscountMultiplier adds value to the "payg_discount_multiplier" field.
func (_u *AccessLevelUpdate) AddPaygDiscountMultiplier(v float64) *AccessLevelUpdate {
	_u.mutation.AddPaygDiscountMultiplier(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccessLevelUpdate) SetUpdatedAt(v time.Time) *AccessLevelUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddAutoUserIDs adds the "auto_users" edge to the User entity by IDs.
func (_u *AccessLevelUpdate) AddAutoUserIDs(ids ...int64) *AccessLevelUpdate {
	_u.mutation.AddAutoUserIDs(ids...)
	return _u
}

// AddAutoUsers adds the "auto_users" edges to the User entity.
func (_u *AccessLevelUpdate) AddAutoUsers(v ...*User) *AccessLevelUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAutoUserIDs(ids...)
}

// AddManualUserIDs adds the "manual_users" edge to the User entity by IDs.
func (_u *AccessLevelUpdate) AddManualUserIDs(ids ...int64) *AccessLevelUpdate {
	_u.mutation.AddManualUserIDs(ids...)
	return _u
}

// AddManualUsers adds the "manual_users" edges to the User entity.
func (_u *AccessLevelUpdate) AddManualUsers(v ...*User) *AccessLevelUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddManualUserIDs(ids...)
}

// AddRequiredGroupIDs adds the "required_groups" edge to the Group entity by IDs.
func (_u *AccessLevelUpdate) AddRequiredGroupIDs(ids ...int64) *AccessLevelUpdate {
	_u.mutation.AddRequiredGroupIDs(ids...)
	return _u
}

// AddRequiredGroups adds the "required_groups" edges to the Group entity.
func (_u *AccessLevelUpdate) AddRequiredGroups(v ...*Group) *AccessLevelUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRequiredGroupIDs(ids...)
}

// Mutation returns the AccessLevelMutation object of the builder.
func (_u *AccessLevelUpdate) Mutation() *AccessLevelMutation {
	return _u.mutation
}

// ClearAutoUsers clears all "auto_users" edges to the User entity.
func (_u *AccessLevelUpdate) ClearAutoUsers() *AccessLevelUpdate {
	_u.mutation.ClearAutoUsers()
	return _u
}

// RemoveAutoUserIDs removes the "auto_users" edge to User entities by IDs.
func (_u *AccessLevelUpdate) RemoveAutoUserIDs(ids ...int64) *AccessLevelUpdate {
	_u.mutation.RemoveAutoUserIDs(ids...)
	return _u
}

// RemoveAutoUsers removes "auto_users" edges to User entities.
func (_u *AccessLevelUpdate) RemoveAutoUsers(v ...*User) *AccessLevelUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAutoUserIDs(ids...)
}

// ClearManualUsers clears all "manual_users" edges to the User entity.
func (_u *AccessLevelUpdate) ClearManualUsers() *AccessLevelUpdate {
	_u.mutation.ClearManualUsers()
	return _u
}

// RemoveManualUserIDs removes the "manual_users" edge to User entities by IDs.
func (_u *AccessLevelUpdate) RemoveManualUserIDs(ids ...int64) *AccessLevelUpdate {
	_u.mutation.RemoveManualUserIDs(ids...)
	return _u
}

// RemoveManualUsers removes "manual_users" edges to User entities.
func (_u *AccessLevelUpdate) RemoveManualUsers(v ...*User) *AccessLevelUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveManualUserIDs(ids...)
}

// ClearRequiredGroups clears all "required_groups" edges to the Group entity.
func (_u *AccessLevelUpdate) ClearRequiredGroups() *AccessLevelUpdate {
	_u.mutation.ClearRequiredGroups()
	return _u
}

// RemoveRequiredGroupIDs removes the "required_groups" edge to Group entities by IDs.
func (_u *AccessLevelUpdate) RemoveRequiredGroupIDs(ids ...int64) *AccessLevelUpdate {
	_u.mutation.RemoveRequiredGroupIDs(ids...)
	return _u
}

// RemoveRequiredGroups removes "required_groups" edges to Group entities.
func (_u *AccessLevelUpdate) RemoveRequiredGroups(v ...*Group) *AccessLevelUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRequiredGroupIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccessLevelUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccessLevelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccessLevelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccessLevelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccessLevelUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accesslevel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccessLevelUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := accesslevel.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AccessLevel.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Rank(); ok {
		if err := accesslevel.RankValidator(v); err != nil {
			return &ValidationError{Name: "rank", err: fmt.Errorf(`ent: validator failed for field "AccessLevel.rank": %w`, err)}
		}
	}
	return nil
}

func (_u *AccessLevelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accesslevel.Table, accesslevel.Columns, sqlgraph.NewFieldSpec(accesslevel.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(accesslevel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Rank(); ok {
		_spec.SetField(accesslevel.FieldRank, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRank(); ok {
		_spec.AddField(accesslevel.FieldRank, field.TypeInt, value)
	}
	if value, ok := _u.mutation.BalanceThreshold(); ok {
		_spec.SetField(accesslevel.FieldBalanceThreshold, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceThreshold(); ok {
		_spec.AddField(accesslevel.FieldBalanceThreshold, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PaygDiscountMultiplier(); ok {
		_spec.SetField(accesslevel.FieldPaygDiscountMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPaygDiscountMultiplier(); ok {
		_spec.AddField(accesslevel.FieldPaygDiscountMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accesslevel.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AutoUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accesslevel.AutoUsersTable,
			Columns: []string{accesslevel.AutoUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAutoUsersIDs(); len(nodes) > 0 && !_u.mutation.AutoUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accesslevel.AutoUsersTable,
			Columns: []string{accesslevel.AutoUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AutoUsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accesslevel.AutoUsersTable,
			Columns: []string{accesslevel.AutoUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ManualUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accesslevel.ManualUsersTable,
			Columns: []string{accesslevel.ManualUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedManualUsersIDs(); len(nodes) > 0 && !_u.mutation.ManualUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accesslevel.ManualUsersTable,
			Columns: []string{accesslevel.ManualUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ManualUsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accesslevel.ManualUsersTable,
			Columns: []string{accesslevel.ManualUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RequiredGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accesslevel.RequiredGroupsTable,
			Columns: []string{accesslevel.RequiredGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRequiredGroupsIDs(); len(nodes) > 0 && !_u.mutation.RequiredGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accesslevel.RequiredGroupsTable,
			Columns: []string{accesslevel.RequiredGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RequiredGroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accesslevel.RequiredGroupsTable,
			Columns: []string{accesslevel.RequiredGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accesslevel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccessLevelUpdateOne is the builder for updating a single AccessLevel entity.
type AccessLevelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccessLevelMutation
}

// SetName sets the "name" field.
func (_u *AccessLevelUpdateOne) SetName(v string) *AccessLevelUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AccessLevelUpdateOne) SetNillableName(v *string) *AccessLevelUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetRank sets the "rank" field.
func (_u *AccessLevelUpdateOne) SetRank(v int) *AccessLevelUpdateOne {
	_u.mutation.ResetRank()
	_u.mutation.SetRank(v)
	return _u
}

// SetNillableRank sets the "rank" field if the given value is not nil.
func (_u *AccessLevelUpdateOne) SetNillableRank(v *int) *AccessLevelUpdateOne {
	if v != nil {
		_u.SetRank(*v)
	}
	return _u
}

// AddRank adds value to the "rank" field.
func (_u *AccessLevelUpdateOne) AddRank(v int) *AccessLevelUpdateOne {
	_u.mutation.AddRank(v)
	return _u
}

// SetBalanceThreshold sets the "balance_threshold" field.
func (_u *AccessLevelUpdateOne) SetBalanceThreshold(v float64) *AccessLevelUpdateOne {
	_u.mutation.ResetBalanceThreshold()
	_u.mutation.SetBalanceThreshold(v)
	return _u
}

// SetNillableBalanceThreshold sets the "balance_threshold" field if the given value is not nil.
func (_u *AccessLevelUpdateOne) SetNillableBalanceThreshold(v *float64) *AccessLevelUpdateOne {
	if v != nil {
		_u.SetBalanceThreshold(*v)
	}
	return _u
}

// AddBalanceThreshold adds value to the "balance_threshold" field.
func (_u *AccessLevelUpdateOne) AddBalanceThreshold(v float64) *AccessLevelUpdateOne {
	_u.mutation.AddBalanceThreshold(v)
	return _u
}

// SetPaygDiscountMultiplier sets the "payg_discount_multiplier" field.
func (_u *AccessLevelUpdateOne) SetPaygDiscountMultiplier(v float64) *AccessLevelUpdateOne {
	_u.mutation.ResetPaygDiscountMultiplier()
	_u.mutation.SetPaygDiscountMultiplier(v)
	return _u
}

// SetNillablePaygDiscountMultiplier sets the "payg_discount_multiplier" field if the given value is not nil.
func (_u *AccessLevelUpdateOne) SetNillablePaygDiscountMultiplier(v *float64) *AccessLevelUpdateOne {
	if v != nil {
		_u.SetPaygDiscountMultiplier(*v)
	}
	return _u
}

// AddPaygDiscountMultiplier adds value to the "payg_discount_multiplier" field.
func (_u *AccessLevelUpdateOne) AddPaygDiscountMultiplier(v float64) *AccessLevelUpdateOne {
	_u.mutation.AddPaygDiscountMultiplier(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccessLevelUpdateOne) SetUpdatedAt(v time.Time) *AccessLevelUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddAutoUserIDs adds the "auto_users" edge to the User entity by IDs.
func (_u *AccessLevelUpdateOne) AddAutoUserIDs(ids ...int64) *AccessLevelUpdateOne {
	_u.mutation.AddAutoUserIDs(ids...)
	return _u
}

// AddAutoUsers adds the "auto_users" edges to the User entity.
func (_u *AccessLevelUpdateOne) AddAutoUsers(v ...*User) *AccessLevelUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAutoUserIDs(ids...)
}

// AddManualUserIDs adds the "manual_users" edge to the User entity by IDs.
func (_u *AccessLevelUpdateOne) AddManualUserIDs(ids ...int64) *AccessLevelUpdateOne {
	_u.mutation.AddManualUserIDs(ids...)
	return _u
}

// AddManualUsers adds the "manual_users" edges to the User entity.
func (_u *AccessLevelUpdateOne) AddManualUsers(v ...*User) *AccessLevelUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddManualUserIDs(ids...)
}

// AddRequiredGroupIDs adds the "required_groups" edge to the Group entity by IDs.
func (_u *AccessLevelUpdateOne) AddRequiredGroupIDs(ids ...int64) *AccessLevelUpdateOne {
	_u.mutation.AddRequiredGroupIDs(ids...)
	return _u
}

// AddRequiredGroups adds the "required_groups" edges to the Group entity.
func (_u *AccessLevelUpdateOne) AddRequiredGroups(v ...*Group) *AccessLevelUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRequiredGroupIDs(ids...)
}

// Mutation returns the AccessLevelMutation object of the builder.
func (_u *AccessLevelUpdateOne) Mutation() *AccessLevelMutation {
	return _u.mutation
}

// ClearAutoUsers clears all "auto_users" edges to the User entity.
func (_u *AccessLevelUpdateOne) ClearAutoUsers() *AccessLevelUpdateOne {
	_u.mutation.ClearAutoUsers()
	return _u
}

// RemoveAutoUserIDs removes the "auto_users" edge to User entities by IDs.
func (_u *AccessLevelUpdateOne) RemoveAutoUserIDs(ids ...int64) *AccessLevelUpdateOne {
	_u.mutation.RemoveAutoUserIDs(ids...)
	return _u
}

// RemoveAutoUsers removes "auto_users" edges to User entities.
func (_u *AccessLevelUpdateOne) RemoveAutoUsers(v ...*User) *AccessLevelUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAutoUserIDs(ids...)
}

// ClearManualUsers clears all "manual_users" edges to the User entity.
func (_u *AccessLevelUpdateOne) ClearManualUsers() *AccessLevelUpdateOne {
	_u.mutation.ClearManualUsers()
	return _u
}

// RemoveManualUserIDs removes the "manual_users" edge to User entities by IDs.
func (_u *AccessLevelUpdateOne) RemoveManualUserIDs(ids ...int64) *AccessLevelUpdateOne {
	_u.mutation.RemoveManualUserIDs(ids...)
	return _u
}

// RemoveManualUsers removes "manual_users" edges to User entities.
func (_u *AccessLevelUpdateOne) RemoveManualUsers(v ...*User) *AccessLevelUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveManualUserIDs(ids...)
}

// ClearRequiredGroups clears all "required_groups" edges to the Group entity.
func (_u *AccessLevelUpdateOne) ClearRequiredGroups() *AccessLevelUpdateOne {
	_u.mutation.ClearRequiredGroups()
	return _u
}

// RemoveRequiredGroupIDs removes the "required_groups" edge to Group entities by IDs.
func (_u *AccessLevelUpdateOne) RemoveRequiredGroupIDs(ids ...int64) *AccessLevelUpdateOne {
	_u.mutation.RemoveRequiredGroupIDs(ids...)
	return _u
}

// RemoveRequiredGroups removes "required_groups" edges to Group entities.
func (_u *AccessLevelUpdateOne) RemoveRequiredGroups(v ...*Group) *AccessLevelUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRequiredGroupIDs(ids...)
}

// Where appends a list predicates to the AccessLevelUpdate builder.
func (_u *AccessLevelUpdateOne) Where(ps ...predicate.AccessLevel) *AccessLevelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccessLevelUpdateOne) Select(field string, fields ...string) *AccessLevelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AccessLevel entity.
func (_u *AccessLevelUpdateOne) Save(ctx context.Context) (*AccessLevel, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccessLevelUpdateOne) SaveX(ctx context.Context) *AccessLevel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccessLevelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccessLevelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccessLevelUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accesslevel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccessLevelUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := accesslevel.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AccessLevel.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Rank(); ok {
		if err := accesslevel.RankValidator(v); err != nil {
			return &ValidationError{Name: "rank", err: fmt.Errorf(`ent: validator failed for field "AccessLevel.rank": %w`, err)}
		}
	}
	return nil
}

func (_u *AccessLevelUpdateOne) sqlSave(ctx context.Context) (_node *AccessLevel, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accesslevel.Table, accesslevel.Columns, sqlgraph.NewFieldSpec(accesslevel.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AccessLevel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accesslevel.FieldID)
		for _, f := range fields {
			if !accesslevel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accesslevel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(accesslevel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Rank(); ok {
		_spec.SetField(accesslevel.FieldRank, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRank(); ok {
		_spec.AddField(accesslevel.FieldRank, field.TypeInt, value)
	}
	if value, ok := _u.mutation.BalanceThreshold(); ok {
		_spec.SetField(accesslevel.FieldBalanceThreshold, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceThreshold(); ok {
		_spec.AddField(accesslevel.FieldBalanceThreshold, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PaygDiscountMultiplier(); ok {
		_spec.SetField(accesslevel.FieldPaygDiscountMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPaygDiscountMultiplier(); ok {
		_spec.AddField(accesslevel.FieldPaygDiscountMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accesslevel.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AutoUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accesslevel.AutoUsersTable,
			Columns: []string{accesslevel.AutoUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAutoUsersIDs(); len(nodes) > 0 && !_u.mutation.AutoUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accesslevel.AutoUsersTable,
			Columns: []string{accesslevel.AutoUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AutoUsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accesslevel.AutoUsersTable,
			Columns: []string{accesslevel.AutoUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ManualUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accesslevel.ManualUsersTable,
			Columns: []string{accesslevel.ManualUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedManualUsersIDs(); len(nodes) > 0 && !_u.mutation.ManualUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accesslevel.ManualUsersTable,
			Columns: []string{accesslevel.ManualUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ManualUsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accesslevel.ManualUsersTable,
			Columns: []string{accesslevel.ManualUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RequiredGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accesslevel.RequiredGroupsTable,
			Columns: []string{accesslevel.RequiredGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRequiredGroupsIDs(); len(nodes) > 0 && !_u.mutation.RequiredGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accesslevel.RequiredGroupsTable,
			Columns: []string{accesslevel.RequiredGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RequiredGroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accesslevel.RequiredGroupsTable,
			Columns: []string{accesslevel.RequiredGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AccessLevel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accesslevel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
