// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accesslevel"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// AccessLevelQuery is the builder for querying AccessLevel entities.
type AccessLevelQuery struct {
	config
	ctx                *QueryContext
	order              []accesslevel.OrderOption
	inters             []Interceptor
	predicates         []predicate.AccessLevel
	withAutoUsers      *UserQuery
	withManualUsers    *UserQuery
	withRequiredGroups *GroupQuery
	modifiers          []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AccessLevelQuery builder.
func (_q *AccessLevelQuery) Where(ps ...predicate.AccessLevel) *AccessLevelQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *AccessLevelQuery) Limit(limit int) *AccessLevelQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *AccessLevelQuery) Offset(offset int) *AccessLevelQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *AccessLevelQuery) Unique(unique bool) *AccessLevelQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *AccessLevelQuery) Order(o ...accesslevel.OrderOption) *AccessLevelQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryAutoUsers chains the current query on the "auto_users" edge.
func (_q *AccessLevelQuery) QueryAutoUsers() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(accesslevel.Table, accesslevel.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, accesslevel.AutoUsersTable, accesslevel.AutoUsersColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryManualUsers chains the current query on the "manual_users" edge.
func (_q *AccessLevelQuery) QueryManualUsers() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(accesslevel.Table, accesslevel.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, accesslevel.ManualUsersTable, accesslevel.ManualUsersColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRequiredGroups chains the current query on the "required_groups" edge.
func (_q *AccessLevelQuery) QueryRequiredGroups() *GroupQuery {
	query := (&GroupClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(accesslevel.Table, accesslevel.FieldID, selector),
			sqlgraph.To(group.Table, group.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, accesslevel.RequiredGroupsTable, accesslevel.RequiredGroupsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AccessLevel entity from the query.
// Returns a *NotFoundError when no AccessLevel was found.
func (_q *AccessLevelQuery) First(ctx context.Context) (*AccessLevel, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{accesslevel.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *AccessLevelQuery) FirstX(ctx context.Context) *AccessLevel {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AccessLevel ID from the query.
// Returns a *NotFoundError when no AccessLevel ID was found.
func (_q *AccessLevelQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{accesslevel.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *AccessLevelQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AccessLevel entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AccessLevel entity is found.
// Returns a *NotFoundError when no AccessLevel entities are found.
func (_q *AccessLevelQuery) Only(ctx context.Context) (*AccessLevel, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{accesslevel.Label}
	default:
		return nil, &NotSingularError{accesslevel.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *AccessLevelQuery) OnlyX(ctx context.Context) *AccessLevel {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AccessLevel ID in the query.
// Returns a *NotSingularError when more than one AccessLevel ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *AccessLevelQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{accesslevel.Label}
	default:
		err = &NotSingularError{accesslevel.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *AccessLevelQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AccessLevels.
func (_q *AccessLevelQuery) All(ctx context.Context) ([]*AccessLevel, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AccessLevel, *AccessLevelQuery]()
	return withInterceptors[[]*AccessLevel](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *AccessLevelQuery) AllX(ctx context.Context) []*AccessLevel {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AccessLevel IDs.
func (_q *AccessLevelQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(accesslevel.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *AccessLevelQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *AccessLevelQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*AccessLevelQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *AccessLevelQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *AccessLevelQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *AccessLevelQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AccessLevelQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *AccessLevelQuery) Clone() *AccessLevelQuery {
	if _q == nil {
		return nil
	}
	return &AccessLevelQuery{
		config:             _q.config,
		ctx:                _q.ctx.Clone(),
		order:              append([]accesslevel.OrderOption{}, _q.order...),
		inters:             append([]Interceptor{}, _q.inters...),
		predicates:         append([]predicate.AccessLevel{}, _q.predicates...),
		withAutoUsers:      _q.withAutoUsers.Clone(),
		withManualUsers:    _q.withManualUsers.Clone(),
		withRequiredGroups: _q.withRequiredGroups.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithAutoUsers tells the query-builder to eager-load the nodes that are connected to
// the "auto_users" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AccessLevelQuery) WithAutoUsers(opts ...func(*UserQuery)) *AccessLevelQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAutoUsers = query
	return _q
}

// WithManualUsers tells the query-builder to eager-load the nodes that are connected to
// the "manual_users" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AccessLevelQuery) WithManualUsers(opts ...func(*UserQuery)) *AccessLevelQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withManualUsers = query
	return _q
}

// WithRequiredGroups tells the query-builder to eager-load the nodes that are connected to
// the "required_groups" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AccessLevelQuery) WithRequiredGroups(opts ...func(*GroupQuery)) *AccessLevelQuery {
	query := (&GroupClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRequiredGroups = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AccessLevel.Query().
//		GroupBy(accesslevel.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *AccessLevelQuery) GroupBy(field string, fields ...string) *AccessLevelGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AccessLevelGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = accesslevel.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.AccessLevel.Query().
//		Select(accesslevel.FieldName).
//		Scan(ctx, &v)
func (_q *AccessLevelQuery) Select(fields ...string) *AccessLevelSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &AccessLevelSelect{AccessLevelQuery: _q}
	sbuild.label = accesslevel.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AccessLevelSelect configured with the given aggregations.
func (_q *AccessLevelQuery) Aggregate(fns ...AggregateFunc) *AccessLevelSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *AccessLevelQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !accesslevel.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *AccessLevelQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AccessLevel, error) {
	var (
		nodes       = []*AccessLevel{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withAutoUsers != nil,
			_q.withManualUsers != nil,
			_q.withRequiredGroups != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AccessLevel).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AccessLevel{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withAutoUsers; query != nil {
		if err := _q.loadAutoUsers(ctx, query, nodes,
			func(n *AccessLevel) { n.Edges.AutoUsers = []*User{} },
			func(n *AccessLevel, e *User) { n.Edges.AutoUsers = append(n.Edges.AutoUsers, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withManualUsers; query != nil {
		if err := _q.loadManualUsers(ctx, query, nodes,
			func(n *AccessLevel) { n.Edges.ManualUsers = []*User{} },
			func(n *AccessLevel, e *User) { n.Edges.ManualUsers = append(n.Edges.ManualUsers, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withRequiredGroups; query != nil {
		if err := _q.loadRequiredGroups(ctx, query, nodes,
			func(n *AccessLevel) { n.Edges.RequiredGroups = []*Group{} },
			func(n *AccessLevel, e *Group) { n.Edges.RequiredGroups = append(n.Edges.RequiredGroups, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *AccessLevelQuery) loadAutoUsers(ctx context.Context, query *UserQuery, nodes []*AccessLevel, init func(*AccessLevel), assign func(*AccessLevel, *User)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*AccessLevel)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(user.FieldAutoLevelID)
	}
	query.Where(predicate.User(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(accesslevel.AutoUsersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.AutoLevelID
		if fk == nil {
			return fmt.Errorf(`foreign-key "auto_level_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "auto_level_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *AccessLevelQuery) loadManualUsers(ctx context.Context, query *UserQuery, nodes []*AccessLevel, init func(*AccessLevel), assign func(*AccessLevel, *User)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*AccessLevel)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(user.FieldManualLevelID)
	}
	query.Where(predicate.User(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(accesslevel.ManualUsersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ManualLevelID
		if fk == nil {
			return fmt.Errorf(`foreign-key "manual_level_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "manual_level_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *AccessLevelQuery) loadRequiredGroups(ctx context.Context, query *GroupQuery, nodes []*AccessLevel, init func(*AccessLevel), assign func(*AccessLevel, *Group)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*AccessLevel)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(group.FieldRequiredLevelID)
	}
	query.Where(predicate.Group(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(accesslevel.RequiredGroupsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.RequiredLevelID
		if fk == nil {
			return fmt.Errorf(`foreign-key "required_level_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "required_level_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *AccessLevelQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *AccessLevelQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(accesslevel.Table, accesslevel.Columns, sqlgraph.NewFieldSpec(accesslevel.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accesslevel.FieldID)
		for i := range fields {
			if fields[i] != accesslevel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *AccessLevelQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(accesslevel.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = accesslevel.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *AccessLevelQuery) ForUpdate(opts ...sql.LockOption) *AccessLevelQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *AccessLevelQuery) ForShare(opts ...sql.LockOption) *AccessLevelQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// AccessLevelGroupBy is the group-by builder for AccessLevel entities.
type AccessLevelGroupBy struct {
	selector
	build *AccessLevelQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *AccessLevelGroupBy) Aggregate(fns ...AggregateFunc) *AccessLevelGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *AccessLevelGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AccessLevelQuery, *AccessLevelGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *AccessLevelGroupBy) sqlScan(ctx context.Context, root *AccessLevelQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AccessLevelSelect is the builder for selecting fields of AccessLevel entities.
type AccessLevelSelect struct {
	*AccessLevelQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *AccessLevelSelect) Aggregate(fns ...AggregateFunc) *AccessLevelSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *AccessLevelSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AccessLevelQuery, *AccessLevelSelect](ctx, _s.AccessLevelQuery, _s, _s.inters, v)
}

func (_s *AccessLevelSelect) sqlScan(ctx context.Context, root *AccessLevelQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
