// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accesslevel"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AccessLevelDelete is the builder for deleting a AccessLevel entity.
type AccessLevelDelete struct {
	config
	hooks    []Hook
	mutation *AccessLevelMutation
}

// Where appends a list predicates to the AccessLevelDelete builder.
func (_d *AccessLevelDelete) Where(ps ...predicate.AccessLevel) *AccessLevelDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AccessLevelDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccessLevelDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AccessLevelDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(accesslevel.Table, sqlgraph.NewFieldSpec(accesslevel.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AccessLevelDeleteOne is the builder for deleting a single AccessLevel entity.
type AccessLevelDeleteOne struct {
	_d *AccessLevelDelete
}

// Where appends a list predicates to the AccessLevelDelete builder.
func (_d *AccessLevelDeleteOne) Where(ps ...predicate.AccessLevel) *AccessLevelDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AccessLevelDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{accesslevel.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccessLevelDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
