// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/authidentity"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// AuthIdentityCreate is the builder for creating a AuthIdentity entity.
type AuthIdentityCreate struct {
	config
	mutation *AuthIdentityMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AuthIdentityCreate) SetCreatedAt(v time.Time) *AuthIdentityCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AuthIdentityCreate) SetNillableCreatedAt(v *time.Time) *AuthIdentityCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AuthIdentityCreate) SetUpdatedAt(v time.Time) *AuthIdentityCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AuthIdentityCreate) SetNillableUpdatedAt(v *time.Time) *AuthIdentityCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *AuthIdentityCreate) SetUserID(v int64) *AuthIdentityCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetProvider sets the "provider" field.
func (_c *AuthIdentityCreate) SetProvider(v string) *AuthIdentityCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetSubject sets the "subject" field.
func (_c *AuthIdentityCreate) SetSubject(v string) *AuthIdentityCreate {
	_c.mutation.SetSubject(v)
	return _c
}

// SetVerifiedEmail sets the "verified_email" field.
func (_c *AuthIdentityCreate) SetVerifiedEmail(v string) *AuthIdentityCreate {
	_c.mutation.SetVerifiedEmail(v)
	return _c
}

// SetVerifiedAt sets the "verified_at" field.
func (_c *AuthIdentityCreate) SetVerifiedAt(v time.Time) *AuthIdentityCreate {
	_c.mutation.SetVerifiedAt(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *AuthIdentityCreate) SetUser(v *User) *AuthIdentityCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the AuthIdentityMutation object of the builder.
func (_c *AuthIdentityCreate) Mutation() *AuthIdentityMutation {
	return _c.mutation
}

// Save creates the AuthIdentity in the database.
func (_c *AuthIdentityCreate) Save(ctx context.Context) (*AuthIdentity, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuthIdentityCreate) SaveX(ctx context.Context) *AuthIdentity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthIdentityCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthIdentityCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AuthIdentityCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := authidentity.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := authidentity.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuthIdentityCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AuthIdentity.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AuthIdentity.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "AuthIdentity.user_id"`)}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "AuthIdentity.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := authidentity.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "AuthIdentity.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Subject(); !ok {
		return &ValidationError{Name: "subject", err: errors.New(`ent: missing required field "AuthIdentity.subject"`)}
	}
	if v, ok := _c.mutation.Subject(); ok {
		if err := authidentity.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "AuthIdentity.subject": %w`, err)}
		}
	}
	if _, ok := _c.mutation.VerifiedEmail(); !ok {
		return &ValidationError{Name: "verified_email", err: errors.New(`ent: missing required field "AuthIdentity.verified_email"`)}
	}
	if v, ok := _c.mutation.VerifiedEmail(); ok {
		if err := authidentity.VerifiedEmailValidator(v); err != nil {
			return &ValidationError{Name: "verified_email", err: fmt.Errorf(`ent: validator failed for field "AuthIdentity.verified_email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.VerifiedAt(); !ok {
		return &ValidationError{Name: "verified_at", err: errors.New(`ent: missing required field "AuthIdentity.verified_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "AuthIdentity.user"`)}
	}
	return nil
}

func (_c *AuthIdentityCreate) sqlSave(ctx context.Context) (*AuthIdentity, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuthIdentityCreate) createSpec() (*AuthIdentity, *sqlgraph.CreateSpec) {
	var (
		_node = &AuthIdentity{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(authidentity.Table, sqlgraph.NewFieldSpec(authidentity.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(authidentity.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(authidentity.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(authidentity.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Subject(); ok {
		_spec.SetField(authidentity.FieldSubject, field.TypeString, value)
		_node.Subject = value
	}
	if value, ok := _c.mutation.VerifiedEmail(); ok {
		_spec.SetField(authidentity.FieldVerifiedEmail, field.TypeString, value)
		_node.VerifiedEmail = value
	}
	if value, ok := _c.mutation.VerifiedAt(); ok {
		_spec.SetField(authidentity.FieldVerifiedAt, field.TypeTime, value)
		_node.VerifiedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   authidentity.UserTable,
			Columns: []string{authidentity.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AuthIdentity.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuthIdentityUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AuthIdentityCreate) OnConflict(opts ...sql.ConflictOption) *AuthIdentityUpsertOne {
	_c.conflict = opts
	return &AuthIdentityUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AuthIdentity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AuthIdentityCreate) OnConflictColumns(columns ...string) *AuthIdentityUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AuthIdentityUpsertOne{
		create: _c,
	}
}

type (
	// AuthIdentityUpsertOne is the builder for "upsert"-ing
	//  one AuthIdentity node.
	AuthIdentityUpsertOne struct {
		create *AuthIdentityCreate
	}

	// AuthIdentityUpsert is the "OnConflict" setter.
	AuthIdentityUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AuthIdentityUpsert) SetUpdatedAt(v time.Time) *AuthIdentityUpsert {
	u.Set(authidentity.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AuthIdentityUpsert) UpdateUpdatedAt() *AuthIdentityUpsert {
	u.SetExcluded(authidentity.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *AuthIdentityUpsert) SetUserID(v int64) *AuthIdentityUpsert {
	u.Set(authidentity.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AuthIdentityUpsert) UpdateUserID() *AuthIdentityUpsert {
	u.SetExcluded(authidentity.FieldUserID)
	return u
}

// SetProvider sets the "provider" field.
func (u *AuthIdentityUpsert) SetProvider(v string) *AuthIdentityUpsert {
	u.Set(authidentity.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *AuthIdentityUpsert) UpdateProvider() *AuthIdentityUpsert {
	u.SetExcluded(authidentity.FieldProvider)
	return u
}

// SetSubject sets the "subject" field.
func (u *AuthIdentityUpsert) SetSubject(v string) *AuthIdentityUpsert {
	u.Set(authidentity.FieldSubject, v)
	return u
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *AuthIdentityUpsert) UpdateSubject() *AuthIdentityUpsert {
	u.SetExcluded(authidentity.FieldSubject)
	return u
}

// SetVerifiedEmail sets the "verified_email" field.
func (u *AuthIdentityUpsert) SetVerifiedEmail(v string) *AuthIdentityUpsert {
	u.Set(authidentity.FieldVerifiedEmail, v)
	return u
}

// UpdateVerifiedEmail sets the "verified_email" field to the value that was provided on create.
func (u *AuthIdentityUpsert) UpdateVerifiedEmail() *AuthIdentityUpsert {
	u.SetExcluded(authidentity.FieldVerifiedEmail)
	return u
}

// SetVerifiedAt sets the "verified_at" field.
func (u *AuthIdentityUpsert) SetVerifiedAt(v time.Time) *AuthIdentityUpsert {
	u.Set(authidentity.FieldVerifiedAt, v)
	return u
}

// UpdateVerifiedAt sets the "verified_at" field to the value that was provided on create.
func (u *AuthIdentityUpsert) UpdateVerifiedAt() *AuthIdentityUpsert {
	u.SetExcluded(authidentity.FieldVerifiedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AuthIdentity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AuthIdentityUpsertOne) UpdateNewValues() *AuthIdentityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(authidentity.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AuthIdentity.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AuthIdentityUpsertOne) Ignore() *AuthIdentityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuthIdentityUpsertOne) DoNothing() *AuthIdentityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuthIdentityCreate.OnConflict
// documentation for more info.
func (u *AuthIdentityUpsertOne) Update(set func(*AuthIdentityUpsert)) *AuthIdentityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuthIdentityUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AuthIdentityUpsertOne) SetUpdatedAt(v time.Time) *AuthIdentityUpsertOne {
	return u.Update(func(s *AuthIdentityUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AuthIdentityUpsertOne) UpdateUpdatedAt() *AuthIdentityUpsertOne {
	return u.Update(func(s *AuthIdentityUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *AuthIdentityUpsertOne) SetUserID(v int64) *AuthIdentityUpsertOne {
	return u.Update(func(s *AuthIdentityUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AuthIdentityUpsertOne) UpdateUserID() *AuthIdentityUpsertOne {
	return u.Update(func(s *AuthIdentityUpsert) {
		s.UpdateUserID()
	})
}

// SetProvider sets the "provider" field.
func (u *AuthIdentityUpsertOne) SetProvider(v string) *AuthIdentityUpsertOne {
	return u.Update(func(s *AuthIdentityUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *AuthIdentityUpsertOne) UpdateProvider() *AuthIdentityUpsertOne {
	return u.Update(func(s *AuthIdentityUpsert) {
		s.UpdateProvider()
	})
}

// SetSubject sets the "subject" field.
func (u *AuthIdentityUpsertOne) SetSubject(v string) *AuthIdentityUpsertOne {
	return u.Update(func(s *AuthIdentityUpsert) {
		s.SetSubject(v)
	})
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *AuthIdentityUpsertOne) UpdateSubject() *AuthIdentityUpsertOne {
	return u.Update(func(s *AuthIdentityUpsert) {
		s.UpdateSubject()
	})
}

// SetVerifiedEmail sets the "verified_email" field.
func (u *AuthIdentityUpsertOne) SetVerifiedEmail(v string) *AuthIdentityUpsertOne {
	return u.Update(func(s *AuthIdentityUpsert) {
		s.SetVerifiedEmail(v)
	})
}

// UpdateVerifiedEmail sets the "verified_email" field to the value that was provided on create.
func (u *AuthIdentityUpsertOne) UpdateVerifiedEmail() *AuthIdentityUpsertOne {
	return u.Update(func(s *AuthIdentityUpsert) {
		s.UpdateVerifiedEmail()
	})
}

// SetVerifiedAt sets the "verified_at" field.
func (u *AuthIdentityUpsertOne) SetVerifiedAt(v time.Time) *AuthIdentityUpsertOne {
	return u.Update(func(s *AuthIdentityUpsert) {
		s.SetVerifiedAt(v)
	})
}

// UpdateVerifiedAt sets the "verified_at" field to the value that was provided on create.
func (u *AuthIdentityUpsertOne) UpdateVerifiedAt() *AuthIdentityUpsertOne {
	return u.Update(func(s *AuthIdentityUpsert) {
		s.UpdateVerifiedAt()
	})
}

// Exec executes the query.
func (u *AuthIdentityUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuthIdentityCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuthIdentityUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AuthIdentityUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AuthIdentityUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AuthIdentityCreateBulk is the builder for creating many AuthIdentity entities in bulk.
type AuthIdentityCreateBulk struct {
	config
	err      error
	builders []*AuthIdentityCreate
	conflict []sql.ConflictOption
}

// Save creates the AuthIdentity entities in the database.
func (_c *AuthIdentityCreateBulk) Save(ctx context.Context) ([]*AuthIdentity, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AuthIdentity, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuthIdentityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuthIdentityCreateBulk) SaveX(ctx context.Context) []*AuthIdentity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthIdentityCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthIdentityCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AuthIdentity.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuthIdentityUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AuthIdentityCreateBulk) OnConflict(opts ...sql.ConflictOption) *AuthIdentityUpsertBulk {
	_c.conflict = opts
	return &AuthIdentityUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AuthIdentity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AuthIdentityCreateBulk) OnConflictColumns(columns ...string) *AuthIdentityUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AuthIdentityUpsertBulk{
		create: _c,
	}
}

// AuthIdentityUpsertBulk is the builder for "upsert"-ing
// a bulk of AuthIdentity nodes.
type AuthIdentityUpsertBulk struct {
	create *AuthIdentityCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AuthIdentity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AuthIdentityUpsertBulk) UpdateNewValues() *AuthIdentityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(authidentity.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AuthIdentity.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AuthIdentityUpsertBulk) Ignore() *AuthIdentityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuthIdentityUpsertBulk) DoNothing() *AuthIdentityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuthIdentityCreateBulk.OnConflict
// documentation for more info.
func (u *AuthIdentityUpsertBulk) Update(set func(*AuthIdentityUpsert)) *AuthIdentityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuthIdentityUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AuthIdentityUpsertBulk) SetUpdatedAt(v time.Time) *AuthIdentityUpsertBulk {
	return u.Update(func(s *AuthIdentityUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AuthIdentityUpsertBulk) UpdateUpdatedAt() *AuthIdentityUpsertBulk {
	return u.Update(func(s *AuthIdentityUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *AuthIdentityUpsertBulk) SetUserID(v int64) *AuthIdentityUpsertBulk {
	return u.Update(func(s *AuthIdentityUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AuthIdentityUpsertBulk) UpdateUserID() *AuthIdentityUpsertBulk {
	return u.Update(func(s *AuthIdentityUpsert) {
		s.UpdateUserID()
	})
}

// SetProvider sets the "provider" field.
func (u *AuthIdentityUpsertBulk) SetProvider(v string) *AuthIdentityUpsertBulk {
	return u.Update(func(s *AuthIdentityUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *AuthIdentityUpsertBulk) UpdateProvider() *AuthIdentityUpsertBulk {
	return u.Update(func(s *AuthIdentityUpsert) {
		s.UpdateProvider()
	})
}

// SetSubject sets the "subject" field.
func (u *AuthIdentityUpsertBulk) SetSubject(v string) *AuthIdentityUpsertBulk {
	return u.Update(func(s *AuthIdentityUpsert) {
		s.SetSubject(v)
	})
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *AuthIdentityUpsertBulk) UpdateSubject() *AuthIdentityUpsertBulk {
	return u.Update(func(s *AuthIdentityUpsert) {
		s.UpdateSubject()
	})
}

// SetVerifiedEmail sets the "verified_email" field.
func (u *AuthIdentityUpsertBulk) SetVerifiedEmail(v string) *AuthIdentityUpsertBulk {
	return u.Update(func(s *AuthIdentityUpsert) {
		s.SetVerifiedEmail(v)
	})
}

// UpdateVerifiedEmail sets the "verified_email" field to the value that was provided on create.
func (u *AuthIdentityUpsertBulk) UpdateVerifiedEmail() *AuthIdentityUpsertBulk {
	return u.Update(func(s *AuthIdentityUpsert) {
		s.UpdateVerifiedEmail()
	})
}

// SetVerifiedAt sets the "verified_at" field.
func (u *AuthIdentityUpsertBulk) SetVerifiedAt(v time.Time) *AuthIdentityUpsertBulk {
	return u.Update(func(s *AuthIdentityUpsert) {
		s.SetVerifiedAt(v)
	})
}

// UpdateVerifiedAt sets the "verified_at" field to the value that was provided on create.
func (u *AuthIdentityUpsertBulk) UpdateVerifiedAt() *AuthIdentityUpsertBulk {
	return u.Update(func(s *AuthIdentityUpsert) {
		s.UpdateVerifiedAt()
	})
}

// Exec executes the query.
func (u *AuthIdentityUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AuthIdentityCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuthIdentityCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuthIdentityUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
