// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/oauthregistrationsession"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// OAuthRegistrationSessionDelete is the builder for deleting a OAuthRegistrationSession entity.
type OAuthRegistrationSessionDelete struct {
	config
	hooks    []Hook
	mutation *OAuthRegistrationSessionMutation
}

// Where appends a list predicates to the OAuthRegistrationSessionDelete builder.
func (_d *OAuthRegistrationSessionDelete) Where(ps ...predicate.OAuthRegistrationSession) *OAuthRegistrationSessionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *OAuthRegistrationSessionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OAuthRegistrationSessionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *OAuthRegistrationSessionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(oauthregistrationsession.Table, sqlgraph.NewFieldSpec(oauthregistrationsession.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// OAuthRegistrationSessionDeleteOne is the builder for deleting a single OAuthRegistrationSession entity.
type OAuthRegistrationSessionDeleteOne struct {
	_d *OAuthRegistrationSessionDelete
}

// Where appends a list predicates to the OAuthRegistrationSessionDelete builder.
func (_d *OAuthRegistrationSessionDeleteOne) Where(ps ...predicate.OAuthRegistrationSession) *OAuthRegistrationSessionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *OAuthRegistrationSessionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{oauthregistrationsession.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OAuthRegistrationSessionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
