// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/oauthregistrationsession"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// OAuthRegistrationSessionUpdate is the builder for updating OAuthRegistrationSession entities.
type OAuthRegistrationSessionUpdate struct {
	config
	hooks    []Hook
	mutation *OAuthRegistrationSessionMutation
}

// Where appends a list predicates to the OAuthRegistrationSessionUpdate builder.
func (_u *OAuthRegistrationSessionUpdate) Where(ps ...predicate.OAuthRegistrationSession) *OAuthRegistrationSessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthRegistrationSessionUpdate) SetUpdatedAt(v time.Time) *OAuthRegistrationSessionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *OAuthRegistrationSessionUpdate) SetTokenHash(v string) *OAuthRegistrationSessionUpdate {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *OAuthRegistrationSessionUpdate) SetNillableTokenHash(v *string) *OAuthRegistrationSessionUpdate {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *OAuthRegistrationSessionUpdate) SetProvider(v string) *OAuthRegistrationSessionUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *OAuthRegistrationSessionUpdate) SetNillableProvider(v *string) *OAuthRegistrationSessionUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *OAuthRegistrationSessionUpdate) SetSubject(v string) *OAuthRegistrationSessionUpdate {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *OAuthRegistrationSessionUpdate) SetNillableSubject(v *string) *OAuthRegistrationSessionUpdate {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetVerifiedEmail sets the "verified_email" field.
func (_u *OAuthRegistrationSessionUpdate) SetVerifiedEmail(v string) *OAuthRegistrationSessionUpdate {
	_u.mutation.SetVerifiedEmail(v)
	return _u
}

// SetNillableVerifiedEmail sets the "verified_email" field if the given value is not nil.
func (_u *OAuthRegistrationSessionUpdate) SetNillableVerifiedEmail(v *string) *OAuthRegistrationSessionUpdate {
	if v != nil {
		_u.SetVerifiedEmail(*v)
	}
	return _u
}

// SetUsername sets the "username" field.
func (_u *OAuthRegistrationSessionUpdate) SetUsername(v string) *OAuthRegistrationSessionUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *OAuthRegistrationSessionUpdate) SetNillableUsername(v *string) *OAuthRegistrationSessionUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *OAuthRegistrationSessionUpdate) SetExpiresAt(v time.Time) *OAuthRegistrationSessionUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *OAuthRegistrationSessionUpdate) SetNillableExpiresAt(v *time.Time) *OAuthRegistrationSessionUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// Mutation returns the OAuthRegistrationSessionMutation object of the builder.
func (_u *OAuthRegistrationSessionUpdate) Mutation() *OAuthRegistrationSessionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OAuthRegistrationSessionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthRegistrationSessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OAuthRegistrationSessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthRegistrationSessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthRegistrationSessionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthregistrationsession.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthRegistrationSessionUpdate) check() error {
	if v, ok := _u.mutation.TokenHash(); ok {
		if err := oauthregistrationsession.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "OAuthRegistrationSession.token_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := oauthregistrationsession.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "OAuthRegistrationSession.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Subject(); ok {
		if err := oauthregistrationsession.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "OAuthRegistrationSession.subject": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VerifiedEmail(); ok {
		if err := oauthregistrationsession.VerifiedEmailValidator(v); err != nil {
			return &ValidationError{Name: "verified_email", err: fmt.Errorf(`ent: validator failed for field "OAuthRegistrationSession.verified_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Username(); ok {
		if err := oauthregistrationsession.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "OAuthRegistrationSession.username": %w`, err)}
		}
	}
	return nil
}

func (_u *OAuthRegistrationSessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthregistrationsession.Table, oauthregistrationsession.Columns, sqlgraph.NewFieldSpec(oauthregistrationsession.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthregistrationsession.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(oauthregistrationsession.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(oauthregistrationsession.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(oauthregistrationsession.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.VerifiedEmail(); ok {
		_spec.SetField(oauthregistrationsession.FieldVerifiedEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(oauthregistrationsession.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthregistrationsession.FieldExpiresAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthregistrationsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OAuthRegistrationSessionUpdateOne is the builder for updating a single OAuthRegistrationSession entity.
type OAuthRegistrationSessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OAuthRegistrationSessionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthRegistrationSessionUpdateOne) SetUpdatedAt(v time.Time) *OAuthRegistrationSessionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *OAuthRegistrationSessionUpdateOne) SetTokenHash(v string) *OAuthRegistrationSessionUpdateOne {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *OAuthRegistrationSessionUpdateOne) SetNillableTokenHash(v *string) *OAuthRegistrationSessionUpdateOne {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *OAuthRegistrationSessionUpdateOne) SetProvider(v string) *OAuthRegistrationSessionUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *OAuthRegistrationSessionUpdateOne) SetNillableProvider(v *string) *OAuthRegistrationSessionUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *OAuthRegistrationSessionUpdateOne) SetSubject(v string) *OAuthRegistrationSessionUpdateOne {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *OAuthRegistrationSessionUpdateOne) SetNillableSubject(v *string) *OAuthRegistrationSessionUpdateOne {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetVerifiedEmail sets the "verified_email" field.
func (_u *OAuthRegistrationSessionUpdateOne) SetVerifiedEmail(v string) *OAuthRegistrationSessionUpdateOne {
	_u.mutation.SetVerifiedEmail(v)
	return _u
}

// SetNillableVerifiedEmail sets the "verified_email" field if the given value is not nil.
func (_u *OAuthRegistrationSessionUpdateOne) SetNillableVerifiedEmail(v *string) *OAuthRegistrationSessionUpdateOne {
	if v != nil {
		_u.SetVerifiedEmail(*v)
	}
	return _u
}

// SetUsername sets the "username" field.
func (_u *OAuthRegistrationSessionUpdateOne) SetUsername(v string) *OAuthRegistrationSessionUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *OAuthRegistrationSessionUpdateOne) SetNillableUsername(v *string) *OAuthRegistrationSessionUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *OAuthRegistrationSessionUpdateOne) SetExpiresAt(v time.Time) *OAuthRegistrationSessionUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *OAuthRegistrationSessionUpdateOne) SetNillableExpiresAt(v *time.Time) *OAuthRegistrationSessionUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// Mutation returns the OAuthRegistrationSessionMutation object of the builder.
func (_u *OAuthRegistrationSessionUpdateOne) Mutation() *OAuthRegistrationSessionMutation {
	return _u.mutation
}

// Where appends a list predicates to the OAuthRegistrationSessionUpdate builder.
func (_u *OAuthRegistrationSessionUpdateOne) Where(ps ...predicate.OAuthRegistrationSession) *OAuthRegistrationSessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OAuthRegistrationSessionUpdateOne) Select(field string, fields ...string) *OAuthRegistrationSessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OAuthRegistrationSession entity.
func (_u *OAuthRegistrationSessionUpdateOne) Save(ctx context.Context) (*OAuthRegistrationSession, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthRegistrationSessionUpdateOne) SaveX(ctx context.Context) *OAuthRegistrationSession {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OAuthRegistrationSessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthRegistrationSessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthRegistrationSessionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthregistrationsession.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthRegistrationSessionUpdateOne) check() error {
	if v, ok := _u.mutation.TokenHash(); ok {
		if err := oauthregistrationsession.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "OAuthRegistrationSession.token_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := oauthregistrationsession.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "OAuthRegistrationSession.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Subject(); ok {
		if err := oauthregistrationsession.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "OAuthRegistrationSession.subject": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VerifiedEmail(); ok {
		if err := oauthregistrationsession.VerifiedEmailValidator(v); err != nil {
			return &ValidationError{Name: "verified_email", err: fmt.Errorf(`ent: validator failed for field "OAuthRegistrationSession.verified_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Username(); ok {
		if err := oauthregistrationsession.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "OAuthRegistrationSession.username": %w`, err)}
		}
	}
	return nil
}

func (_u *OAuthRegistrationSessionUpdateOne) sqlSave(ctx context.Context) (_node *OAuthRegistrationSession, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthregistrationsession.Table, oauthregistrationsession.Columns, sqlgraph.NewFieldSpec(oauthregistrationsession.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OAuthRegistrationSession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthregistrationsession.FieldID)
		for _, f := range fields {
			if !oauthregistrationsession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oauthregistrationsession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthregistrationsession.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(oauthregistrationsession.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(oauthregistrationsession.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(oauthregistrationsession.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.VerifiedEmail(); ok {
		_spec.SetField(oauthregistrationsession.FieldVerifiedEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(oauthregistrationsession.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthregistrationsession.FieldExpiresAt, field.TypeTime, value)
	}
	_node = &OAuthRegistrationSession{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthregistrationsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
