// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/oauthregistrationsession"
)

// OAuthRegistrationSessionCreate is the builder for creating a OAuthRegistrationSession entity.
type OAuthRegistrationSessionCreate struct {
	config
	mutation *OAuthRegistrationSessionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *OAuthRegistrationSessionCreate) SetCreatedAt(v time.Time) *OAuthRegistrationSessionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OAuthRegistrationSessionCreate) SetNillableCreatedAt(v *time.Time) *OAuthRegistrationSessionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OAuthRegistrationSessionCreate) SetUpdatedAt(v time.Time) *OAuthRegistrationSessionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OAuthRegistrationSessionCreate) SetNillableUpdatedAt(v *time.Time) *OAuthRegistrationSessionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTokenHash sets the "token_hash" field.
func (_c *OAuthRegistrationSessionCreate) SetTokenHash(v string) *OAuthRegistrationSessionCreate {
	_c.mutation.SetTokenHash(v)
	return _c
}

// SetProvider sets the "provider" field.
func (_c *OAuthRegistrationSessionCreate) SetProvider(v string) *OAuthRegistrationSessionCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetSubject sets the "subject" field.
func (_c *OAuthRegistrationSessionCreate) SetSubject(v string) *OAuthRegistrationSessionCreate {
	_c.mutation.SetSubject(v)
	return _c
}

// SetVerifiedEmail sets the "verified_email" field.
func (_c *OAuthRegistrationSessionCreate) SetVerifiedEmail(v string) *OAuthRegistrationSessionCreate {
	_c.mutation.SetVerifiedEmail(v)
	return _c
}

// SetUsername sets the "username" field.
func (_c *OAuthRegistrationSessionCreate) SetUsername(v string) *OAuthRegistrationSessionCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_c *OAuthRegistrationSessionCreate) SetNillableUsername(v *string) *OAuthRegistrationSessionCreate {
	if v != nil {
		_c.SetUsername(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *OAuthRegistrationSessionCreate) SetExpiresAt(v time.Time) *OAuthRegistrationSessionCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// Mutation returns the OAuthRegistrationSessionMutation object of the builder.
func (_c *OAuthRegistrationSessionCreate) Mutation() *OAuthRegistrationSessionMutation {
	return _c.mutation
}

// Save creates the OAuthRegistrationSession in the database.
func (_c *OAuthRegistrationSessionCreate) Save(ctx context.Context) (*OAuthRegistrationSession, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OAuthRegistrationSessionCreate) SaveX(ctx context.Context) *OAuthRegistrationSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthRegistrationSessionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthRegistrationSessionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OAuthRegistrationSessionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := oauthregistrationsession.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := oauthregistrationsession.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Username(); !ok {
		v := oauthregistrationsession.DefaultUsername
		_c.mutation.SetUsername(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OAuthRegistrationSessionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OAuthRegistrationSession.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OAuthRegistrationSession.updated_at"`)}
	}
	if _, ok := _c.mutation.TokenHash(); !ok {
		return &ValidationError{Name: "token_hash", err: errors.New(`ent: missing required field "OAuthRegistrationSession.token_hash"`)}
	}
	if v, ok := _c.mutation.TokenHash(); ok {
		if err := oauthregistrationsession.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "OAuthRegistrationSession.token_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "OAuthRegistrationSession.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := oauthregistrationsession.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "OAuthRegistrationSession.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Subject(); !ok {
		return &ValidationError{Name: "subject", err: errors.New(`ent: missing required field "OAuthRegistrationSession.subject"`)}
	}
	if v, ok := _c.mutation.Subject(); ok {
		if err := oauthregistrationsession.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "OAuthRegistrationSession.subject": %w`, err)}
		}
	}
	if _, ok := _c.mutation.VerifiedEmail(); !ok {
		return &ValidationError{Name: "verified_email", err: errors.New(`ent: missing required field "OAuthRegistrationSession.verified_email"`)}
	}
	if v, ok := _c.mutation.VerifiedEmail(); ok {
		if err := oauthregistrationsession.VerifiedEmailValidator(v); err != nil {
			return &ValidationError{Name: "verified_email", err: fmt.Errorf(`ent: validator failed for field "OAuthRegistrationSession.verified_email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "OAuthRegistrationSession.username"`)}
	}
	if v, ok := _c.mutation.Username(); ok {
		if err := oauthregistrationsession.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "OAuthRegistrationSession.username": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "OAuthRegistrationSession.expires_at"`)}
	}
	return nil
}

func (_c *OAuthRegistrationSessionCreate) sqlSave(ctx context.Context) (*OAuthRegistrationSession, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OAuthRegistrationSessionCreate) createSpec() (*OAuthRegistrationSession, *sqlgraph.CreateSpec) {
	var (
		_node = &OAuthRegistrationSession{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oauthregistrationsession.Table, sqlgraph.NewFieldSpec(oauthregistrationsession.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(oauthregistrationsession.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthregistrationsession.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.TokenHash(); ok {
		_spec.SetField(oauthregistrationsession.FieldTokenHash, field.TypeString, value)
		_node.TokenHash = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(oauthregistrationsession.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Subject(); ok {
		_spec.SetField(oauthregistrationsession.FieldSubject, field.TypeString, value)
		_node.Subject = value
	}
	if value, ok := _c.mutation.VerifiedEmail(); ok {
		_spec.SetField(oauthregistrationsession.FieldVerifiedEmail, field.TypeString, value)
		_node.VerifiedEmail = value
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(oauthregistrationsession.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthregistrationsession.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OAuthRegistrationSession.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OAuthRegistrationSessionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OAuthRegistrationSessionCreate) OnConflict(opts ...sql.ConflictOption) *OAuthRegistrationSessionUpsertOne {
	_c.conflict = opts
	return &OAuthRegistrationSessionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OAuthRegistrationSession.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OAuthRegistrationSessionCreate) OnConflictColumns(columns ...string) *OAuthRegistrationSessionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OAuthRegistrationSessionUpsertOne{
		create: _c,
	}
}

type (
	// OAuthRegistrationSessionUpsertOne is the builder for "upsert"-ing
	//  one OAuthRegistrationSession node.
	OAuthRegistrationSessionUpsertOne struct {
		create *OAuthRegistrationSessionCreate
	}

	// OAuthRegistrationSessionUpsert is the "OnConflict" setter.
	OAuthRegistrationSessionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthRegistrationSessionUpsert) SetUpdatedAt(v time.Time) *OAuthRegistrationSessionUpsert {
	u.Set(oauthregistrationsession.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthRegistrationSessionUpsert) UpdateUpdatedAt() *OAuthRegistrationSessionUpsert {
	u.SetExcluded(oauthregistrationsession.FieldUpdatedAt)
	return u
}

// SetTokenHash sets the "token_hash" field.
func (u *OAuthRegistrationSessionUpsert) SetTokenHash(v string) *OAuthRegistrationSessionUpsert {
	u.Set(oauthregistrationsession.FieldTokenHash, v)
	return u
}

// UpdateTokenHash sets the "token_hash" field to the value that was provided on create.
func (u *OAuthRegistrationSessionUpsert) UpdateTokenHash() *OAuthRegistrationSessionUpsert {
	u.SetExcluded(oauthregistrationsession.FieldTokenHash)
	return u
}

// SetProvider sets the "provider" field.
func (u *OAuthRegistrationSessionUpsert) SetProvider(v string) *OAuthRegistrationSessionUpsert {
	u.Set(oauthregistrationsession.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *OAuthRegistrationSessionUpsert) UpdateProvider() *OAuthRegistrationSessionUpsert {
	u.SetExcluded(oauthregistrationsession.FieldProvider)
	return u
}

// SetSubject sets the "subject" field.
func (u *OAuthRegistrationSessionUpsert) SetSubject(v string) *OAuthRegistrationSessionUpsert {
	u.Set(oauthregistrationsession.FieldSubject, v)
	return u
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *OAuthRegistrationSessionUpsert) UpdateSubject() *OAuthRegistrationSessionUpsert {
	u.SetExcluded(oauthregistrationsession.FieldSubject)
	return u
}

// SetVerifiedEmail sets the "verified_email" field.
func (u *OAuthRegistrationSessionUpsert) SetVerifiedEmail(v string) *OAuthRegistrationSessionUpsert {
	u.Set(oauthregistrationsession.FieldVerifiedEmail, v)
	return u
}

// UpdateVerifiedEmail sets the "verified_email" field to the value that was provided on create.
func (u *OAuthRegistrationSessionUpsert) UpdateVerifiedEmail() *OAuthRegistrationSessionUpsert {
	u.SetExcluded(oauthregistrationsession.FieldVerifiedEmail)
	return u
}

// SetUsername sets the "username" field.
func (u *OAuthRegistrationSessionUpsert) SetUsername(v string) *OAuthRegistrationSessionUpsert {
	u.Set(oauthregistrationsession.FieldUsername, v)
	return u
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *OAuthRegistrationSessionUpsert) UpdateUsername() *OAuthRegistrationSessionUpsert {
	u.SetExcluded(oauthregistrationsession.FieldUsername)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *OAuthRegistrationSessionUpsert) SetExpiresAt(v time.Time) *OAuthRegistrationSessionUpsert {
	u.Set(oauthregistrationsession.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *OAuthRegistrationSessionUpsert) UpdateExpiresAt() *OAuthRegistrationSessionUpsert {
	u.SetExcluded(oauthregistrationsession.FieldExpiresAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.OAuthRegistrationSession.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OAuthRegistrationSessionUpsertOne) UpdateNewValues() *OAuthRegistrationSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(oauthregistrationsession.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OAuthRegistrationSession.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OAuthRegistrationSessionUpsertOne) Ignore() *OAuthRegistrationSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OAuthRegistrationSessionUpsertOne) DoNothing() *OAuthRegistrationSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OAuthRegistrationSessionCreate.OnConflict
// documentation for more info.
func (u *OAuthRegistrationSessionUpsertOne) Update(set func(*OAuthRegistrationSessionUpsert)) *OAuthRegistrationSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OAuthRegistrationSessionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthRegistrationSessionUpsertOne) SetUpdatedAt(v time.Time) *OAuthRegistrationSessionUpsertOne {
	return u.Update(func(s *OAuthRegistrationSessionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthRegistrationSessionUpsertOne) UpdateUpdatedAt() *OAuthRegistrationSessionUpsertOne {
	return u.Update(func(s *OAuthRegistrationSessionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetTokenHash sets the "token_hash" field.
func (u *OAuthRegistrationSessionUpsertOne) SetTokenHash(v string) *OAuthRegistrationSessionUpsertOne {
	return u.Update(func(s *OAuthRegistrationSessionUpsert) {
		s.SetTokenHash(v)
	})
}

// UpdateTokenHash sets the "token_hash" field to the value that was provided on create.
func (u *OAuthRegistrationSessionUpsertOne) UpdateTokenHash() *OAuthRegistrationSessionUpsertOne {
	return u.Update(func(s *OAuthRegistrationSessionUpsert) {
		s.UpdateTokenHash()
	})
}

// SetProvider sets the "provider" field.
func (u *OAuthRegistrationSessionUpsertOne) SetProvider(v string) *OAuthRegistrationSessionUpsertOne {
	return u.Update(func(s *OAuthRegistrationSessionUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *OAuthRegistrationSessionUpsertOne) UpdateProvider() *OAuthRegistrationSessionUpsertOne {
	return u.Update(func(s *OAuthRegistrationSessionUpsert) {
		s.UpdateProvider()
	})
}

// SetSubject sets the "subject" field.
func (u *OAuthRegistrationSessionUpsertOne) SetSubject(v string) *OAuthRegistrationSessionUpsertOne {
	return u.Update(func(s *OAuthRegistrationSessionUpsert) {
		s.SetSubject(v)
	})
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *OAuthRegistrationSessionUpsertOne) UpdateSubject() *OAuthRegistrationSessionUpsertOne {
	return u.Update(func(s *OAuthRegistrationSessionUpsert) {
		s.UpdateSubject()
	})
}

// SetVerifiedEmail sets the "verified_email" field.
func (u *OAuthRegistrationSessionUpsertOne) SetVerifiedEmail(v string) *OAuthRegistrationSessionUpsertOne {
	return u.Update(func(s *OAuthRegistrationSessionUpsert) {
		s.SetVerifiedEmail(v)
	})
}

// UpdateVerifiedEmail sets the "verified_email" field to the value that was provided on create.
func (u *OAuthRegistrationSessionUpsertOne) UpdateVerifiedEmail() *OAuthRegistrationSessionUpsertOne {
	return u.Update(func(s *OAuthRegistrationSessionUpsert) {
		s.UpdateVerifiedEmail()
	})
}

// SetUsername sets the "username" field.
func (u *OAuthRegistrationSessionUpsertOne) SetUsername(v string) *OAuthRegistrationSessionUpsertOne {
	return u.Update(func(s *OAuthRegistrationSessionUpsert) {
		s.SetUsername(v)
	})
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *OAuthRegistrationSessionUpsertOne) UpdateUsername() *OAuthRegistrationSessionUpsertOne {
	return u.Update(func(s *OAuthRegistrationSessionUpsert) {
		s.UpdateUsername()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *OAuthRegistrationSessionUpsertOne) SetExpiresAt(v time.Time) *OAuthRegistrationSessionUpsertOne {
	return u.Update(func(s *OAuthRegistrationSessionUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *OAuthRegistrationSessionUpsertOne) UpdateExpiresAt() *OAuthRegistrationSessionUpsertOne {
	return u.Update(func(s *OAuthRegistrationSessionUpsert) {
		s.UpdateExpiresAt()
	})
}

// Exec executes the query.
func (u *OAuthRegistrationSessionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OAuthRegistrationSessionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OAuthRegistrationSessionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OAuthRegistrationSessionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OAuthRegistrationSessionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OAuthRegistrationSessionCreateBulk is the builder for creating many OAuthRegistrationSession entities in bulk.
type OAuthRegistrationSessionCreateBulk struct {
	config
	err      error
	builders []*OAuthRegistrationSessionCreate
	conflict []sql.ConflictOption
}

// Save creates the OAuthRegistrationSession entities in the database.
func (_c *OAuthRegistrationSessionCreateBulk) Save(ctx context.Context) ([]*OAuthRegistrationSession, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OAuthRegistrationSession, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OAuthRegistrationSessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OAuthRegistrationSessionCreateBulk) SaveX(ctx context.Context) []*OAuthRegistrationSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthRegistrationSessionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthRegistrationSessionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OAuthRegistrationSession.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OAuthRegistrationSessionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OAuthRegistrationSessionCreateBulk) OnConflict(opts ...sql.ConflictOption) *OAuthRegistrationSessionUpsertBulk {
	_c.conflict = opts
	return &OAuthRegistrationSessionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OAuthRegistrationSession.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OAuthRegistrationSessionCreateBulk) OnConflictColumns(columns ...string) *OAuthRegistrationSessionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OAuthRegistrationSessionUpsertBulk{
		create: _c,
	}
}

// OAuthRegistrationSessionUpsertBulk is the builder for "upsert"-ing
// a bulk of OAuthRegistrationSession nodes.
type OAuthRegistrationSessionUpsertBulk struct {
	create *OAuthRegistrationSessionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OAuthRegistrationSession.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OAuthRegistrationSessionUpsertBulk) UpdateNewValues() *OAuthRegistrationSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(oauthregistrationsession.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OAuthRegistrationSession.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OAuthRegistrationSessionUpsertBulk) Ignore() *OAuthRegistrationSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OAuthRegistrationSessionUpsertBulk) DoNothing() *OAuthRegistrationSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OAuthRegistrationSessionCreateBulk.OnConflict
// documentation for more info.
func (u *OAuthRegistrationSessionUpsertBulk) Update(set func(*OAuthRegistrationSessionUpsert)) *OAuthRegistrationSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OAuthRegistrationSessionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthRegistrationSessionUpsertBulk) SetUpdatedAt(v time.Time) *OAuthRegistrationSessionUpsertBulk {
	return u.Update(func(s *OAuthRegistrationSessionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthRegistrationSessionUpsertBulk) UpdateUpdatedAt() *OAuthRegistrationSessionUpsertBulk {
	return u.Update(func(s *OAuthRegistrationSessionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetTokenHash sets the "token_hash" field.
func (u *OAuthRegistrationSessionUpsertBulk) SetTokenHash(v string) *OAuthRegistrationSessionUpsertBulk {
	return u.Update(func(s *OAuthRegistrationSessionUpsert) {
		s.SetTokenHash(v)
	})
}

// UpdateTokenHash sets the "token_hash" field to the value that was provided on create.
func (u *OAuthRegistrationSessionUpsertBulk) UpdateTokenHash() *OAuthRegistrationSessionUpsertBulk {
	return u.Update(func(s *OAuthRegistrationSessionUpsert) {
		s.UpdateTokenHash()
	})
}

// SetProvider sets the "provider" field.
func (u *OAuthRegistrationSessionUpsertBulk) SetProvider(v string) *OAuthRegistrationSessionUpsertBulk {
	return u.Update(func(s *OAuthRegistrationSessionUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *OAuthRegistrationSessionUpsertBulk) UpdateProvider() *OAuthRegistrationSessionUpsertBulk {
	return u.Update(func(s *OAuthRegistrationSessionUpsert) {
		s.UpdateProvider()
	})
}

// SetSubject sets the "subject" field.
func (u *OAuthRegistrationSessionUpsertBulk) SetSubject(v string) *OAuthRegistrationSessionUpsertBulk {
	return u.Update(func(s *OAuthRegistrationSessionUpsert) {
		s.SetSubject(v)
	})
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *OAuthRegistrationSessionUpsertBulk) UpdateSubject() *OAuthRegistrationSessionUpsertBulk {
	return u.Update(func(s *OAuthRegistrationSessionUpsert) {
		s.UpdateSubject()
	})
}

// SetVerifiedEmail sets the "verified_email" field.
func (u *OAuthRegistrationSessionUpsertBulk) SetVerifiedEmail(v string) *OAuthRegistrationSessionUpsertBulk {
	return u.Update(func(s *OAuthRegistrationSessionUpsert) {
		s.SetVerifiedEmail(v)
	})
}

// UpdateVerifiedEmail sets the "verified_email" field to the value that was provided on create.
func (u *OAuthRegistrationSessionUpsertBulk) UpdateVerifiedEmail() *OAuthRegistrationSessionUpsertBulk {
	return u.Update(func(s *OAuthRegistrationSessionUpsert) {
		s.UpdateVerifiedEmail()
	})
}

// SetUsername sets the "username" field.
func (u *OAuthRegistrationSessionUpsertBulk) SetUsername(v string) *OAuthRegistrationSessionUpsertBulk {
	return u.Update(func(s *OAuthRegistrationSessionUpsert) {
		s.SetUsername(v)
	})
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *OAuthRegistrationSessionUpsertBulk) UpdateUsername() *OAuthRegistrationSessionUpsertBulk {
	return u.Update(func(s *OAuthRegistrationSessionUpsert) {
		s.UpdateUsername()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *OAuthRegistrationSessionUpsertBulk) SetExpiresAt(v time.Time) *OAuthRegistrationSessionUpsertBulk {
	return u.Update(func(s *OAuthRegistrationSessionUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *OAuthRegistrationSessionUpsertBulk) UpdateExpiresAt() *OAuthRegistrationSessionUpsertBulk {
	return u.Update(func(s *OAuthRegistrationSessionUpsert) {
		s.UpdateExpiresAt()
	})
}

// Exec executes the query.
func (u *OAuthRegistrationSessionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OAuthRegistrationSessionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OAuthRegistrationSessionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OAuthRegistrationSessionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
