// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
)

// PaymentOrder is the model entity for the PaymentOrder schema.
type PaymentOrder struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// UserEmail holds the value of the "user_email" field.
	UserEmail string `json:"user_email,omitempty"`
	// UserName holds the value of the "user_name" field.
	UserName string `json:"user_name,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount float64 `json:"amount,omitempty"`
	// PayAmount holds the value of the "pay_amount" field.
	PayAmount float64 `json:"pay_amount,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// BalanceCreditRate holds the value of the "balance_credit_rate" field.
	BalanceCreditRate float64 `json:"balance_credit_rate,omitempty"`
	// FeeRate holds the value of the "fee_rate" field.
	FeeRate float64 `json:"fee_rate,omitempty"`
	// RechargeCode holds the value of the "recharge_code" field.
	RechargeCode string `json:"recharge_code,omitempty"`
	// OrderType holds the value of the "order_type" field.
	OrderType string `json:"order_type,omitempty"`
	// PlanID holds the value of the "plan_id" field.
	PlanID *int64 `json:"plan_id,omitempty"`
	// SubscriptionGroupID holds the value of the "subscription_group_id" field.
	SubscriptionGroupID *int64 `json:"subscription_group_id,omitempty"`
	// SubscriptionDays holds the value of the "subscription_days" field.
	SubscriptionDays *int `json:"subscription_days,omitempty"`
	// OutTradeNo holds the value of the "out_trade_no" field.
	OutTradeNo string `json:"out_trade_no,omitempty"`
	// PaymentType holds the value of the "payment_type" field.
	PaymentType string `json:"payment_type,omitempty"`
	// ProviderKey holds the value of the "provider_key" field.
	ProviderKey string `json:"provider_key,omitempty"`
	// ProviderInstanceID holds the value of the "provider_instance_id" field.
	ProviderInstanceID int64 `json:"provider_instance_id,omitempty"`
	// ProviderSnapshotEncrypted holds the value of the "provider_snapshot_encrypted" field.
	ProviderSnapshotEncrypted string `json:"provider_snapshot_encrypted,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// PaymentTradeNo holds the value of the "payment_trade_no" field.
	PaymentTradeNo string `json:"payment_trade_no,omitempty"`
	// PayURL holds the value of the "pay_url" field.
	PayURL *string `json:"pay_url,omitempty"`
	// QrCode holds the value of the "qr_code" field.
	QrCode *string `json:"qr_code,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// PaidAt holds the value of the "paid_at" field.
	PaidAt *time.Time `json:"paid_at,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// FailedAt holds the value of the "failed_at" field.
	FailedAt *time.Time `json:"failed_at,omitempty"`
	// FailedReason holds the value of the "failed_reason" field.
	FailedReason *string `json:"failed_reason,omitempty"`
	// RefundMode holds the value of the "refund_mode" field.
	RefundMode string `json:"refund_mode,omitempty"`
	// RefundAmount holds the value of the "refund_amount" field.
	RefundAmount float64 `json:"refund_amount,omitempty"`
	// RefundReason holds the value of the "refund_reason" field.
	RefundReason *string `json:"refund_reason,omitempty"`
	// RefundExternalReference holds the value of the "refund_external_reference" field.
	RefundExternalReference *string `json:"refund_external_reference,omitempty"`
	// RefundRequestedBy holds the value of the "refund_requested_by" field.
	RefundRequestedBy string `json:"refund_requested_by,omitempty"`
	// RefundRequestedAt holds the value of the "refund_requested_at" field.
	RefundRequestedAt *time.Time `json:"refund_requested_at,omitempty"`
	// RefundProviderCallStartedAt holds the value of the "refund_provider_call_started_at" field.
	RefundProviderCallStartedAt *time.Time `json:"refund_provider_call_started_at,omitempty"`
	// RefundedAt holds the value of the "refunded_at" field.
	RefundedAt *time.Time `json:"refunded_at,omitempty"`
	// RefundID holds the value of the "refund_id" field.
	RefundID string `json:"refund_id,omitempty"`
	// RefundEntitlementReversed holds the value of the "refund_entitlement_reversed" field.
	RefundEntitlementReversed bool `json:"refund_entitlement_reversed,omitempty"`
	// RefundEntitlementSnapshot holds the value of the "refund_entitlement_snapshot" field.
	RefundEntitlementSnapshot string `json:"refund_entitlement_snapshot,omitempty"`
	// RefundForce holds the value of the "refund_force" field.
	RefundForce bool `json:"refund_force,omitempty"`
	// RefundError holds the value of the "refund_error" field.
	RefundError *string `json:"refund_error,omitempty"`
	// ClientIP holds the value of the "client_ip" field.
	ClientIP string `json:"client_ip,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PaymentOrder) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case paymentorder.FieldRefundEntitlementReversed, paymentorder.FieldRefundForce:
			values[i] = new(sql.NullBool)
		case paymentorder.FieldAmount, paymentorder.FieldPayAmount, paymentorder.FieldBalanceCreditRate, paymentorder.FieldFeeRate, paymentorder.FieldRefundAmount:
			values[i] = new(sql.NullFloat64)
		case paymentorder.FieldID, paymentorder.FieldUserID, paymentorder.FieldPlanID, paymentorder.FieldSubscriptionGroupID, paymentorder.FieldSubscriptionDays, paymentorder.FieldProviderInstanceID:
			values[i] = new(sql.NullInt64)
		case paymentorder.FieldUserEmail, paymentorder.FieldUserName, paymentorder.FieldCurrency, paymentorder.FieldRechargeCode, paymentorder.FieldOrderType, paymentorder.FieldOutTradeNo, paymentorder.FieldPaymentType, paymentorder.FieldProviderKey, paymentorder.FieldProviderSnapshotEncrypted, paymentorder.FieldStatus, paymentorder.FieldPaymentTradeNo, paymentorder.FieldPayURL, paymentorder.FieldQrCode, paymentorder.FieldFailedReason, paymentorder.FieldRefundMode, paymentorder.FieldRefundReason, paymentorder.FieldRefundExternalReference, paymentorder.FieldRefundRequestedBy, paymentorder.FieldRefundID, paymentorder.FieldRefundEntitlementSnapshot, paymentorder.FieldRefundError, paymentorder.FieldClientIP:
			values[i] = new(sql.NullString)
		case paymentorder.FieldExpiresAt, paymentorder.FieldPaidAt, paymentorder.FieldCompletedAt, paymentorder.FieldFailedAt, paymentorder.FieldRefundRequestedAt, paymentorder.FieldRefundProviderCallStartedAt, paymentorder.FieldRefundedAt, paymentorder.FieldCreatedAt, paymentorder.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PaymentOrder fields.
func (_m *PaymentOrder) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case paymentorder.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case paymentorder.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case paymentorder.FieldUserEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_email", values[i])
			} else if value.Valid {
				_m.UserEmail = value.String
			}
		case paymentorder.FieldUserName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_name", values[i])
			} else if value.Valid {
				_m.UserName = value.String
			}
		case paymentorder.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case paymentorder.FieldPayAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field pay_amount", values[i])
			} else if value.Valid {
				_m.PayAmount = value.Float64
			}
		case paymentorder.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case paymentorder.FieldBalanceCreditRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance_credit_rate", values[i])
			} else if value.Valid {
				_m.BalanceCreditRate = value.Float64
			}
		case paymentorder.FieldFeeRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field fee_rate", values[i])
			} else if value.Valid {
				_m.FeeRate = value.Float64
			}
		case paymentorder.FieldRechargeCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field recharge_code", values[i])
			} else if value.Valid {
				_m.RechargeCode = value.String
			}
		case paymentorder.FieldOrderType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field order_type", values[i])
			} else if value.Valid {
				_m.OrderType = value.String
			}
		case paymentorder.FieldPlanID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field plan_id", values[i])
			} else if value.Valid {
				_m.PlanID = new(int64)
				*_m.PlanID = value.Int64
			}
		case paymentorder.FieldSubscriptionGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_group_id", values[i])
			} else if value.Valid {
				_m.SubscriptionGroupID = new(int64)
				*_m.SubscriptionGroupID = value.Int64
			}
		case paymentorder.FieldSubscriptionDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_days", values[i])
			} else if value.Valid {
				_m.SubscriptionDays = new(int)
				*_m.SubscriptionDays = int(value.Int64)
			}
		case paymentorder.FieldOutTradeNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field out_trade_no", values[i])
			} else if value.Valid {
				_m.OutTradeNo = value.String
			}
		case paymentorder.FieldPaymentType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payment_type", values[i])
			} else if value.Valid {
				_m.PaymentType = value.String
			}
		case paymentorder.FieldProviderKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_key", values[i])
			} else if value.Valid {
				_m.ProviderKey = value.String
			}
		case paymentorder.FieldProviderInstanceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field provider_instance_id", values[i])
			} else if value.Valid {
				_m.ProviderInstanceID = value.Int64
			}
		case paymentorder.FieldProviderSnapshotEncrypted:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_snapshot_encrypted", values[i])
			} else if value.Valid {
				_m.ProviderSnapshotEncrypted = value.String
			}
		case paymentorder.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case paymentorder.FieldPaymentTradeNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payment_trade_no", values[i])
			} else if value.Valid {
				_m.PaymentTradeNo = value.String
			}
		case paymentorder.FieldPayURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pay_url", values[i])
			} else if value.Valid {
				_m.PayURL = new(string)
				*_m.PayURL = value.String
			}
		case paymentorder.FieldQrCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field qr_code", values[i])
			} else if value.Valid {
				_m.QrCode = new(string)
				*_m.QrCode = value.String
			}
		case paymentorder.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case paymentorder.FieldPaidAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field paid_at", values[i])
			} else if value.Valid {
				_m.PaidAt = new(time.Time)
				*_m.PaidAt = value.Time
			}
		case paymentorder.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		case paymentorder.FieldFailedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field failed_at", values[i])
			} else if value.Valid {
				_m.FailedAt = new(time.Time)
				*_m.FailedAt = value.Time
			}
		case paymentorder.FieldFailedReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field failed_reason", values[i])
			} else if value.Valid {
				_m.FailedReason = new(string)
				*_m.FailedReason = value.String
			}
		case paymentorder.FieldRefundMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refund_mode", values[i])
			} else if value.Valid {
				_m.RefundMode = value.String
			}
		case paymentorder.FieldRefundAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field refund_amount", values[i])
			} else if value.Valid {
				_m.RefundAmount = value.Float64
			}
		case paymentorder.FieldRefundReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refund_reason", values[i])
			} else if value.Valid {
				_m.RefundReason = new(string)
				*_m.RefundReason = value.String
			}
		case paymentorder.FieldRefundExternalReference:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refund_external_reference", values[i])
			} else if value.Valid {
				_m.RefundExternalReference = new(string)
				*_m.RefundExternalReference = value.String
			}
		case paymentorder.FieldRefundRequestedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refund_requested_by", values[i])
			} else if value.Valid {
				_m.RefundRequestedBy = value.String
			}
		case paymentorder.FieldRefundRequestedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field refund_requested_at", values[i])
			} else if value.Valid {
				_m.RefundRequestedAt = new(time.Time)
				*_m.RefundRequestedAt = value.Time
			}
		case paymentorder.FieldRefundProviderCallStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field refund_provider_call_started_at", values[i])
			} else if value.Valid {
				_m.RefundProviderCallStartedAt = new(time.Time)
				*_m.RefundProviderCallStartedAt = value.Time
			}
		case paymentorder.FieldRefundedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field refunded_at", values[i])
			} else if value.Valid {
				_m.RefundedAt = new(time.Time)
				*_m.RefundedAt = value.Time
			}
		case paymentorder.FieldRefundID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refund_id", values[i])
			} else if value.Valid {
				_m.RefundID = value.String
			}
		case paymentorder.FieldRefundEntitlementReversed:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field refund_entitlement_reversed", values[i])
			} else if value.Valid {
				_m.RefundEntitlementReversed = value.Bool
			}
		case paymentorder.FieldRefundEntitlementSnapshot:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refund_entitlement_snapshot", values[i])
			} else if value.Valid {
				_m.RefundEntitlementSnapshot = value.String
			}
		case paymentorder.FieldRefundForce:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field refund_force", values[i])
			} else if value.Valid {
				_m.RefundForce = value.Bool
			}
		case paymentorder.FieldRefundError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refund_error", values[i])
			} else if value.Valid {
				_m.RefundError = new(string)
				*_m.RefundError = value.String
			}
		case paymentorder.FieldClientIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_ip", values[i])
			} else if value.Valid {
				_m.ClientIP = value.String
			}
		case paymentorder.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case paymentorder.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PaymentOrder.
// This includes values selected through modifiers, order, etc.
func (_m *PaymentOrder) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PaymentOrder.
// Note that you need to call PaymentOrder.Unwrap() before calling this method if this PaymentOrder
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PaymentOrder) Update() *PaymentOrderUpdateOne {
	return NewPaymentOrderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PaymentOrder entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PaymentOrder) Unwrap() *PaymentOrder {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PaymentOrder is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PaymentOrder) String() string {
	var builder strings.Builder
	builder.WriteString("PaymentOrder(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("user_email=")
	builder.WriteString(_m.UserEmail)
	builder.WriteString(", ")
	builder.WriteString("user_name=")
	builder.WriteString(_m.UserName)
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("pay_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.PayAmount))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("balance_credit_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.BalanceCreditRate))
	builder.WriteString(", ")
	builder.WriteString("fee_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.FeeRate))
	builder.WriteString(", ")
	builder.WriteString("recharge_code=")
	builder.WriteString(_m.RechargeCode)
	builder.WriteString(", ")
	builder.WriteString("order_type=")
	builder.WriteString(_m.OrderType)
	builder.WriteString(", ")
	if v := _m.PlanID; v != nil {
		builder.WriteString("plan_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SubscriptionGroupID; v != nil {
		builder.WriteString("subscription_group_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SubscriptionDays; v != nil {
		builder.WriteString("subscription_days=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("out_trade_no=")
	builder.WriteString(_m.OutTradeNo)
	builder.WriteString(", ")
	builder.WriteString("payment_type=")
	builder.WriteString(_m.PaymentType)
	builder.WriteString(", ")
	builder.WriteString("provider_key=")
	builder.WriteString(_m.ProviderKey)
	builder.WriteString(", ")
	builder.WriteString("provider_instance_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProviderInstanceID))
	builder.WriteString(", ")
	builder.WriteString("provider_snapshot_encrypted=")
	builder.WriteString(_m.ProviderSnapshotEncrypted)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("payment_trade_no=")
	builder.WriteString(_m.PaymentTradeNo)
	builder.WriteString(", ")
	if v := _m.PayURL; v != nil {
		builder.WriteString("pay_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.QrCode; v != nil {
		builder.WriteString("qr_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.PaidAt; v != nil {
		builder.WriteString("paid_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.FailedAt; v != nil {
		builder.WriteString("failed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.FailedReason; v != nil {
		builder.WriteString("failed_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("refund_mode=")
	builder.WriteString(_m.RefundMode)
	builder.WriteString(", ")
	builder.WriteString("refund_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.RefundAmount))
	builder.WriteString(", ")
	if v := _m.RefundReason; v != nil {
		builder.WriteString("refund_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.RefundExternalReference; v != nil {
		builder.WriteString("refund_external_reference=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("refund_requested_by=")
	builder.WriteString(_m.RefundRequestedBy)
	builder.WriteString(", ")
	if v := _m.RefundRequestedAt; v != nil {
		builder.WriteString("refund_requested_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.RefundProviderCallStartedAt; v != nil {
		builder.WriteString("refund_provider_call_started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.RefundedAt; v != nil {
		builder.WriteString("refunded_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("refund_id=")
	builder.WriteString(_m.RefundID)
	builder.WriteString(", ")
	builder.WriteString("refund_entitlement_reversed=")
	builder.WriteString(fmt.Sprintf("%v", _m.RefundEntitlementReversed))
	builder.WriteString(", ")
	builder.WriteString("refund_entitlement_snapshot=")
	builder.WriteString(_m.RefundEntitlementSnapshot)
	builder.WriteString(", ")
	builder.WriteString("refund_force=")
	builder.WriteString(fmt.Sprintf("%v", _m.RefundForce))
	builder.WriteString(", ")
	if v := _m.RefundError; v != nil {
		builder.WriteString("refund_error=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("client_ip=")
	builder.WriteString(_m.ClientIP)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PaymentOrders is a parsable slice of PaymentOrder.
type PaymentOrders []*PaymentOrder
