// Code generated by ent, DO NOT EDIT.

package oauthregistrationsession

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldEQ(FieldUpdatedAt, v))
}

// TokenHash applies equality check predicate on the "token_hash" field. It's identical to TokenHashEQ.
func TokenHash(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldEQ(FieldTokenHash, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldEQ(FieldProvider, v))
}

// Subject applies equality check predicate on the "subject" field. It's identical to SubjectEQ.
func Subject(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldEQ(FieldSubject, v))
}

// VerifiedEmail applies equality check predicate on the "verified_email" field. It's identical to VerifiedEmailEQ.
func VerifiedEmail(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldEQ(FieldVerifiedEmail, v))
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldEQ(FieldUsername, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldLTE(FieldUpdatedAt, v))
}

// TokenHashEQ applies the EQ predicate on the "token_hash" field.
func TokenHashEQ(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldEQ(FieldTokenHash, v))
}

// TokenHashNEQ applies the NEQ predicate on the "token_hash" field.
func TokenHashNEQ(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldNEQ(FieldTokenHash, v))
}

// TokenHashIn applies the In predicate on the "token_hash" field.
func TokenHashIn(vs ...string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldIn(FieldTokenHash, vs...))
}

// TokenHashNotIn applies the NotIn predicate on the "token_hash" field.
func TokenHashNotIn(vs ...string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldNotIn(FieldTokenHash, vs...))
}

// TokenHashGT applies the GT predicate on the "token_hash" field.
func TokenHashGT(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldGT(FieldTokenHash, v))
}

// TokenHashGTE applies the GTE predicate on the "token_hash" field.
func TokenHashGTE(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldGTE(FieldTokenHash, v))
}

// TokenHashLT applies the LT predicate on the "token_hash" field.
func TokenHashLT(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldLT(FieldTokenHash, v))
}

// TokenHashLTE applies the LTE predicate on the "token_hash" field.
func TokenHashLTE(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldLTE(FieldTokenHash, v))
}

// TokenHashContains applies the Contains predicate on the "token_hash" field.
func TokenHashContains(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldContains(FieldTokenHash, v))
}

// TokenHashHasPrefix applies the HasPrefix predicate on the "token_hash" field.
func TokenHashHasPrefix(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldHasPrefix(FieldTokenHash, v))
}

// TokenHashHasSuffix applies the HasSuffix predicate on the "token_hash" field.
func TokenHashHasSuffix(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldHasSuffix(FieldTokenHash, v))
}

// TokenHashEqualFold applies the EqualFold predicate on the "token_hash" field.
func TokenHashEqualFold(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldEqualFold(FieldTokenHash, v))
}

// TokenHashContainsFold applies the ContainsFold predicate on the "token_hash" field.
func TokenHashContainsFold(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldContainsFold(FieldTokenHash, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldContainsFold(FieldProvider, v))
}

// SubjectEQ applies the EQ predicate on the "subject" field.
func SubjectEQ(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldEQ(FieldSubject, v))
}

// SubjectNEQ applies the NEQ predicate on the "subject" field.
func SubjectNEQ(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldNEQ(FieldSubject, v))
}

// SubjectIn applies the In predicate on the "subject" field.
func SubjectIn(vs ...string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldIn(FieldSubject, vs...))
}

// SubjectNotIn applies the NotIn predicate on the "subject" field.
func SubjectNotIn(vs ...string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldNotIn(FieldSubject, vs...))
}

// SubjectGT applies the GT predicate on the "subject" field.
func SubjectGT(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldGT(FieldSubject, v))
}

// SubjectGTE applies the GTE predicate on the "subject" field.
func SubjectGTE(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldGTE(FieldSubject, v))
}

// SubjectLT applies the LT predicate on the "subject" field.
func SubjectLT(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldLT(FieldSubject, v))
}

// SubjectLTE applies the LTE predicate on the "subject" field.
func SubjectLTE(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldLTE(FieldSubject, v))
}

// SubjectContains applies the Contains predicate on the "subject" field.
func SubjectContains(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldContains(FieldSubject, v))
}

// SubjectHasPrefix applies the HasPrefix predicate on the "subject" field.
func SubjectHasPrefix(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldHasPrefix(FieldSubject, v))
}

// SubjectHasSuffix applies the HasSuffix predicate on the "subject" field.
func SubjectHasSuffix(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldHasSuffix(FieldSubject, v))
}

// SubjectEqualFold applies the EqualFold predicate on the "subject" field.
func SubjectEqualFold(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldEqualFold(FieldSubject, v))
}

// SubjectContainsFold applies the ContainsFold predicate on the "subject" field.
func SubjectContainsFold(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldContainsFold(FieldSubject, v))
}

// VerifiedEmailEQ applies the EQ predicate on the "verified_email" field.
func VerifiedEmailEQ(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldEQ(FieldVerifiedEmail, v))
}

// VerifiedEmailNEQ applies the NEQ predicate on the "verified_email" field.
func VerifiedEmailNEQ(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldNEQ(FieldVerifiedEmail, v))
}

// VerifiedEmailIn applies the In predicate on the "verified_email" field.
func VerifiedEmailIn(vs ...string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldIn(FieldVerifiedEmail, vs...))
}

// VerifiedEmailNotIn applies the NotIn predicate on the "verified_email" field.
func VerifiedEmailNotIn(vs ...string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldNotIn(FieldVerifiedEmail, vs...))
}

// VerifiedEmailGT applies the GT predicate on the "verified_email" field.
func VerifiedEmailGT(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldGT(FieldVerifiedEmail, v))
}

// VerifiedEmailGTE applies the GTE predicate on the "verified_email" field.
func VerifiedEmailGTE(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldGTE(FieldVerifiedEmail, v))
}

// VerifiedEmailLT applies the LT predicate on the "verified_email" field.
func VerifiedEmailLT(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldLT(FieldVerifiedEmail, v))
}

// VerifiedEmailLTE applies the LTE predicate on the "verified_email" field.
func VerifiedEmailLTE(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldLTE(FieldVerifiedEmail, v))
}

// VerifiedEmailContains applies the Contains predicate on the "verified_email" field.
func VerifiedEmailContains(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldContains(FieldVerifiedEmail, v))
}

// VerifiedEmailHasPrefix applies the HasPrefix predicate on the "verified_email" field.
func VerifiedEmailHasPrefix(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldHasPrefix(FieldVerifiedEmail, v))
}

// VerifiedEmailHasSuffix applies the HasSuffix predicate on the "verified_email" field.
func VerifiedEmailHasSuffix(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldHasSuffix(FieldVerifiedEmail, v))
}

// VerifiedEmailEqualFold applies the EqualFold predicate on the "verified_email" field.
func VerifiedEmailEqualFold(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldEqualFold(FieldVerifiedEmail, v))
}

// VerifiedEmailContainsFold applies the ContainsFold predicate on the "verified_email" field.
func VerifiedEmailContainsFold(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldContainsFold(FieldVerifiedEmail, v))
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldEQ(FieldUsername, v))
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldNEQ(FieldUsername, v))
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldIn(FieldUsername, vs...))
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldNotIn(FieldUsername, vs...))
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldGT(FieldUsername, v))
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldGTE(FieldUsername, v))
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldLT(FieldUsername, v))
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldLTE(FieldUsername, v))
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldContains(FieldUsername, v))
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldHasPrefix(FieldUsername, v))
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldHasSuffix(FieldUsername, v))
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldEqualFold(FieldUsername, v))
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldContainsFold(FieldUsername, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.FieldLTE(FieldExpiresAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OAuthRegistrationSession) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OAuthRegistrationSession) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OAuthRegistrationSession) predicate.OAuthRegistrationSession {
	return predicate.OAuthRegistrationSession(sql.NotPredicates(p))
}
