// Code generated by ent, DO NOT EDIT.

package accesslevel

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the accesslevel type in the database.
	Label = "access_level"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldRank holds the string denoting the rank field in the database.
	FieldRank = "rank"
	// FieldBalanceThreshold holds the string denoting the balance_threshold field in the database.
	FieldBalanceThreshold = "balance_threshold"
	// FieldPaygDiscountMultiplier holds the string denoting the payg_discount_multiplier field in the database.
	FieldPaygDiscountMultiplier = "payg_discount_multiplier"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeAutoUsers holds the string denoting the auto_users edge name in mutations.
	EdgeAutoUsers = "auto_users"
	// EdgeManualUsers holds the string denoting the manual_users edge name in mutations.
	EdgeManualUsers = "manual_users"
	// EdgeRequiredGroups holds the string denoting the required_groups edge name in mutations.
	EdgeRequiredGroups = "required_groups"
	// Table holds the table name of the accesslevel in the database.
	Table = "access_levels"
	// AutoUsersTable is the table that holds the auto_users relation/edge.
	AutoUsersTable = "users"
	// AutoUsersInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	AutoUsersInverseTable = "users"
	// AutoUsersColumn is the table column denoting the auto_users relation/edge.
	AutoUsersColumn = "auto_level_id"
	// ManualUsersTable is the table that holds the manual_users relation/edge.
	ManualUsersTable = "users"
	// ManualUsersInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	ManualUsersInverseTable = "users"
	// ManualUsersColumn is the table column denoting the manual_users relation/edge.
	ManualUsersColumn = "manual_level_id"
	// RequiredGroupsTable is the table that holds the required_groups relation/edge.
	RequiredGroupsTable = "groups"
	// RequiredGroupsInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	RequiredGroupsInverseTable = "groups"
	// RequiredGroupsColumn is the table column denoting the required_groups relation/edge.
	RequiredGroupsColumn = "required_level_id"
)

// Columns holds all SQL columns for accesslevel fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldRank,
	FieldBalanceThreshold,
	FieldPaygDiscountMultiplier,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// RankValidator is a validator for the "rank" field. It is called by the builders before save.
	RankValidator func(int) error
	// DefaultBalanceThreshold holds the default value on creation for the "balance_threshold" field.
	DefaultBalanceThreshold float64
	// DefaultPaygDiscountMultiplier holds the default value on creation for the "payg_discount_multiplier" field.
	DefaultPaygDiscountMultiplier float64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the AccessLevel queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByRank orders the results by the rank field.
func ByRank(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRank, opts...).ToFunc()
}

// ByBalanceThreshold orders the results by the balance_threshold field.
func ByBalanceThreshold(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceThreshold, opts...).ToFunc()
}

// ByPaygDiscountMultiplier orders the results by the payg_discount_multiplier field.
func ByPaygDiscountMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaygDiscountMultiplier, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByAutoUsersCount orders the results by auto_users count.
func ByAutoUsersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAutoUsersStep(), opts...)
	}
}

// ByAutoUsers orders the results by auto_users terms.
func ByAutoUsers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAutoUsersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByManualUsersCount orders the results by manual_users count.
func ByManualUsersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newManualUsersStep(), opts...)
	}
}

// ByManualUsers orders the results by manual_users terms.
func ByManualUsers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newManualUsersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByRequiredGroupsCount orders the results by required_groups count.
func ByRequiredGroupsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRequiredGroupsStep(), opts...)
	}
}

// ByRequiredGroups orders the results by required_groups terms.
func ByRequiredGroups(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRequiredGroupsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newAutoUsersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AutoUsersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AutoUsersTable, AutoUsersColumn),
	)
}
func newManualUsersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ManualUsersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ManualUsersTable, ManualUsersColumn),
	)
}
func newRequiredGroupsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RequiredGroupsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RequiredGroupsTable, RequiredGroupsColumn),
	)
}
