// Code generated by ent, DO NOT EDIT.

package accesslevel

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldEQ(FieldName, v))
}

// Rank applies equality check predicate on the "rank" field. It's identical to RankEQ.
func Rank(v int) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldEQ(FieldRank, v))
}

// BalanceThreshold applies equality check predicate on the "balance_threshold" field. It's identical to BalanceThresholdEQ.
func BalanceThreshold(v float64) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldEQ(FieldBalanceThreshold, v))
}

// PaygDiscountMultiplier applies equality check predicate on the "payg_discount_multiplier" field. It's identical to PaygDiscountMultiplierEQ.
func PaygDiscountMultiplier(v float64) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldEQ(FieldPaygDiscountMultiplier, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldContainsFold(FieldName, v))
}

// RankEQ applies the EQ predicate on the "rank" field.
func RankEQ(v int) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldEQ(FieldRank, v))
}

// RankNEQ applies the NEQ predicate on the "rank" field.
func RankNEQ(v int) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldNEQ(FieldRank, v))
}

// RankIn applies the In predicate on the "rank" field.
func RankIn(vs ...int) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldIn(FieldRank, vs...))
}

// RankNotIn applies the NotIn predicate on the "rank" field.
func RankNotIn(vs ...int) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldNotIn(FieldRank, vs...))
}

// RankGT applies the GT predicate on the "rank" field.
func RankGT(v int) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldGT(FieldRank, v))
}

// RankGTE applies the GTE predicate on the "rank" field.
func RankGTE(v int) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldGTE(FieldRank, v))
}

// RankLT applies the LT predicate on the "rank" field.
func RankLT(v int) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldLT(FieldRank, v))
}

// RankLTE applies the LTE predicate on the "rank" field.
func RankLTE(v int) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldLTE(FieldRank, v))
}

// BalanceThresholdEQ applies the EQ predicate on the "balance_threshold" field.
func BalanceThresholdEQ(v float64) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldEQ(FieldBalanceThreshold, v))
}

// BalanceThresholdNEQ applies the NEQ predicate on the "balance_threshold" field.
func BalanceThresholdNEQ(v float64) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldNEQ(FieldBalanceThreshold, v))
}

// BalanceThresholdIn applies the In predicate on the "balance_threshold" field.
func BalanceThresholdIn(vs ...float64) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldIn(FieldBalanceThreshold, vs...))
}

// BalanceThresholdNotIn applies the NotIn predicate on the "balance_threshold" field.
func BalanceThresholdNotIn(vs ...float64) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldNotIn(FieldBalanceThreshold, vs...))
}

// BalanceThresholdGT applies the GT predicate on the "balance_threshold" field.
func BalanceThresholdGT(v float64) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldGT(FieldBalanceThreshold, v))
}

// BalanceThresholdGTE applies the GTE predicate on the "balance_threshold" field.
func BalanceThresholdGTE(v float64) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldGTE(FieldBalanceThreshold, v))
}

// BalanceThresholdLT applies the LT predicate on the "balance_threshold" field.
func BalanceThresholdLT(v float64) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldLT(FieldBalanceThreshold, v))
}

// BalanceThresholdLTE applies the LTE predicate on the "balance_threshold" field.
func BalanceThresholdLTE(v float64) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldLTE(FieldBalanceThreshold, v))
}

// PaygDiscountMultiplierEQ applies the EQ predicate on the "payg_discount_multiplier" field.
func PaygDiscountMultiplierEQ(v float64) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldEQ(FieldPaygDiscountMultiplier, v))
}

// PaygDiscountMultiplierNEQ applies the NEQ predicate on the "payg_discount_multiplier" field.
func PaygDiscountMultiplierNEQ(v float64) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldNEQ(FieldPaygDiscountMultiplier, v))
}

// PaygDiscountMultiplierIn applies the In predicate on the "payg_discount_multiplier" field.
func PaygDiscountMultiplierIn(vs ...float64) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldIn(FieldPaygDiscountMultiplier, vs...))
}

// PaygDiscountMultiplierNotIn applies the NotIn predicate on the "payg_discount_multiplier" field.
func PaygDiscountMultiplierNotIn(vs ...float64) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldNotIn(FieldPaygDiscountMultiplier, vs...))
}

// PaygDiscountMultiplierGT applies the GT predicate on the "payg_discount_multiplier" field.
func PaygDiscountMultiplierGT(v float64) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldGT(FieldPaygDiscountMultiplier, v))
}

// PaygDiscountMultiplierGTE applies the GTE predicate on the "payg_discount_multiplier" field.
func PaygDiscountMultiplierGTE(v float64) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldGTE(FieldPaygDiscountMultiplier, v))
}

// PaygDiscountMultiplierLT applies the LT predicate on the "payg_discount_multiplier" field.
func PaygDiscountMultiplierLT(v float64) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldLT(FieldPaygDiscountMultiplier, v))
}

// PaygDiscountMultiplierLTE applies the LTE predicate on the "payg_discount_multiplier" field.
func PaygDiscountMultiplierLTE(v float64) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldLTE(FieldPaygDiscountMultiplier, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AccessLevel {
	return predicate.AccessLevel(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasAutoUsers applies the HasEdge predicate on the "auto_users" edge.
func HasAutoUsers() predicate.AccessLevel {
	return predicate.AccessLevel(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AutoUsersTable, AutoUsersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAutoUsersWith applies the HasEdge predicate on the "auto_users" edge with a given conditions (other predicates).
func HasAutoUsersWith(preds ...predicate.User) predicate.AccessLevel {
	return predicate.AccessLevel(func(s *sql.Selector) {
		step := newAutoUsersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasManualUsers applies the HasEdge predicate on the "manual_users" edge.
func HasManualUsers() predicate.AccessLevel {
	return predicate.AccessLevel(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ManualUsersTable, ManualUsersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasManualUsersWith applies the HasEdge predicate on the "manual_users" edge with a given conditions (other predicates).
func HasManualUsersWith(preds ...predicate.User) predicate.AccessLevel {
	return predicate.AccessLevel(func(s *sql.Selector) {
		step := newManualUsersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRequiredGroups applies the HasEdge predicate on the "required_groups" edge.
func HasRequiredGroups() predicate.AccessLevel {
	return predicate.AccessLevel(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RequiredGroupsTable, RequiredGroupsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRequiredGroupsWith applies the HasEdge predicate on the "required_groups" edge with a given conditions (other predicates).
func HasRequiredGroupsWith(preds ...predicate.Group) predicate.AccessLevel {
	return predicate.AccessLevel(func(s *sql.Selector) {
		step := newRequiredGroupsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AccessLevel) predicate.AccessLevel {
	return predicate.AccessLevel(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AccessLevel) predicate.AccessLevel {
	return predicate.AccessLevel(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AccessLevel) predicate.AccessLevel {
	return predicate.AccessLevel(sql.NotPredicates(p))
}
